### ISSUE TITLE
ACI VNet with Windows Containers

### ISSUE THREAD

**Issue by prochnowc** [virtual-kubelet/azure-aci#100]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate): Azure
Version (e.g. 0.1, 0.2-beta) : 0.5.0
Install Method (e.g. Helm Chart, ): Helm Chart

### Issue Details

Virtual windows nodes cannot use a VNet.

When I deploy a windows container with configured ACI VNet I receive the following error in the log output of the virtual-kubelet pod:

`Network profile is not supported before version '2018-07-01'`

Seems that ACI already supports VNet's for Windows Container but virtual-kubelet does not use the correct Azure API version.

**Comment by feiskyer** [comment]
VNet for Windows ACI is not supported (Linux is supported).

**Comment by chrye** [comment]
@feiskyer Can you please clarify what "VNet for Windows ACI is not supported" mean?

**Comment by feiskyer** [comment]
Please see the ACI docs here https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet
