### ISSUE TITLE
Error: YAML parse error on virtual-kubelet/templates/deployment.yaml: error converting YAML to JSON: yaml: control characters are not allowed

### ISSUE THREAD

**Issue by bdfrost** [virtual-kubelet/azure-aci#109]
---

### Environment summary

Provider: Azure ACI

Version: latest

K8s Master Info: Azure AKS

Install Method: Helm, Chart

### Issue Details
When I follow the instructions, I get the error below ("Error: YAML parse error on virtual-kubelet/templates/deployment.yaml: error converting YAML to JSON: yaml: control characters are not allowed")

I see that virtual-kubelet-latest.tgz is a broken tar as it results in some non-directories being made:

drwxrwxr-x   2 bfrost bfrost     4096 Jan 20 17:28 virtual-kubelet
-rwxr-xr-x   1 bfrost bfrost      450 Dec 31  1969 virtual-kubelet\templates\clusterrolebinding.yaml
-rwxr-xr-x   1 bfrost bfrost     4686 Dec 31  1969 virtual-kubelet\templates\deployment.yaml
-rwxr-xr-x   1 bfrost bfrost      854 Dec 31  1969 virtual-kubelet\templates\_helpers.tpl
-rwxr-xr-x   1 bfrost bfrost      444 Dec 31  1969 virtual-kubelet\templates\NOTES.txt
-rwxr-xr-x   1 bfrost bfrost     1976 Dec 31  1969 virtual-kubelet\templates\secret.yaml
-rwxr-xr-x   1 bfrost bfrost      171 Dec 31  1969 virtual-kubelet\templates\serviceaccount.yaml
-rwxr-xr-x   1 bfrost bfrost      751 Dec 31  1969 virtual-kubelet\templates\tests\helloworld.yaml

^^^ That might be the result of tar'ing on windows. Above is the result on both Mac and Linux.

To get around this issue, I cloned the whole repo and pointed the helm install at the chart directory and I still get the error.

### Repo Steps
$ export VK_RELEASE=virtual-kubelet-latest
$ export MASTER_URI=$( kubectl cluster-info | grep master | awk '{ print $6 }' )
$ export RELEASE_NAME=virtual-kubelet
$ export VK_RELEASE=virtual-kubelet-latest
$ export NODE_NAME=virtual-kubelet
$ export CHART_URL=https://github.com/virtual-kubelet/virtual-kubelet/raw/master/charts/$VK_RELEASE.tgz

$ helm install "$CHART_URL" --name "$RELEASE_NAME" --set provider=azure --set providers.azure.targetAKS=true --set providers.azure.masterUri=$MASTER_URI

Error: YAML parse error on virtual-kubelet/templates/deployment.yaml: error converting YAML to JSON: yaml: control characters are not allowed

----
On a side note, this is a really cool project. Thanks for all of the hard work.

**Comment by feiskyer** [comment]
Issues should have already been fixed.

**Comment by chrye** [comment]
@feiskyer I have exactly the same issue. I am running all the commands in cloudshell, and I got same error with either a Linux node or a Windows node.

**Comment by feiskyer** [comment]
@chrye  could you share you detailed steps (with credential removed)?

**Comment by chrye** [comment]
@feiskyer I just made it work after many different tries. When I tried to use helm install with variables, it always fails. Then I took out the variables and put the value in and it just worked. So I am all good. Thanks!

**Comment by feiskyer** [comment]
@chrye glad to hear it already works. which version of helm are you using?

**Comment by chrye** [comment]
@feiskyer helm-v3.5.4-windows-amd64.
locally I am using helm-v3.5.4-windows-amd64. But eventually I got it working on cloudshell, so it is always the latest version on cloudshell environment. It's been maintained by platform.

**Comment by feiskyer** [comment]
couldn't repro the issue. I think there're something wrong when parsing master URL, it should be `kubectl cluster-info| awk '/Kubernetes control plane/{print $7}'`.
