### ISSUE TITLE
Istio Sidecar error - "SecretVolumesNotSupportedOnWindows"

### ISSUE THREAD

**Issue by dylanjohnsonsfo** [virtual-kubelet/azure-aci#114]
---

### Environment summary

Provider (Azure)

### Issue Details

The istio sidecar will not start even with ```automountServiceAccountToken: false``` added to the istio-sidecar-injector spec.  

Error = "SecretVolumesNotSupportedOnWindows"

**Comment by feiskyer** [comment]
this is not supported by ACI service.
