### ISSUE TITLE
Unauthorized error with Windows virtual nodes on AKS

### ISSUE THREAD

**Issue by MattJeanes** [virtual-kubelet/azure-aci#121]
Hi there, I am attempting to set up Windows ACI virtual nodes using this project along with the built-in Azure functionality for Linux nodes. The built-in Linux nodes are working well but the Windows one is writing an error every 10 seconds or so:

`time="2021-01-29T16:36:28Z" level=info msg="Unauthorized, ok: false" node=virtual-kubelet-aci-win operatingSystem=Windows provider=azure watchedNamespace=`

This is the command used to install the project:

```bash
helm upgrade --install --wait --atomic --debug \
"virtual-kubelet-aci-win" \
"https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-1.3.2.tgz" \
--namespace "virtual-kubelet-aci-win" \
--set "provider=azure" \
--set "providers.azure.targetAKS=true" \
--set "providers.azure.masterUri=https://example-aks-dns-1234abcd.hcp.westeurope.azmk8s.io:443" \
--set "nodeName=virtual-kubelet-aci-win" \
--set "nodeOsType=Windows"
```

Our Azure cluster is using standard RBAC, Azure CNI with a subnet already created as part of the built-in Azure Linux ACI feature.

**Comment by feiskyer** [comment]
@MattJeanes I couldn't reproduce the issue with the same steps. Have you deployed successfully for Linux OS type?

**Comment by MattJeanes** [comment]
We are using the built-in AKS feature for virtual Linux nodes, would it cause any problems if I try to deploy this with the Linux nodeOsType since there would be two of them then?

![image](https://user-images.githubusercontent.com/2363642/106446192-d9a09e00-6477-11eb-811b-3348c2a42936.png)

Our cluster is running Kubernetes 1.19.6

If there's anymore debug information I can provide I'm happy to help out, I couldn't find any more.

**Comment by feiskyer** [comment]
No, it should work just as expected for Linux nodes.

Because ACI doesn't support VNet integration yet, AKS virtual nodes only support Linux nodes.

**Comment by MattJeanes** [comment]
@feiskyer I have tried that now, exactly the same setup but just changed Windows to Linux for nodeOsType and it still comes back with essentially the same error message 🙁

```log
time="2021-02-04T00:52:59Z" level=info msg=Initialized node=virtual-kubelet-aci-win operatingSystem=Linux provider=azure watchedNamespace=
time="2021-02-04T00:52:59Z" level=info msg="Pod cache in-sync" node=virtual-kubelet-aci-win operatingSystem=Linux provider=azure watchedNamespace=
time="2021-02-04T00:52:59Z" level=info msg="starting workers" node=virtual-kubelet-aci-win operatingSystem=Linux provider=azure watchedNamespace=
time="2021-02-04T00:52:59Z" level=info msg="started workers" node=virtual-kubelet-aci-win operatingSystem=Linux provider=azure watchedNamespace=
time="2021-02-04T00:53:05Z" level=info msg="Unauthorized, ok: false" node=virtual-kubelet-aci-win operatingSystem=Linux provider=azure watchedNamespace=
time="2021-02-04T00:53:06Z" level=info msg="Unauthorized, ok: false" node=virtual-kubelet-aci-win operatingSystem=Linux provider=azure watchedNamespace=
```

I have attached the azdeploy.json (had to rename it to .txt for GitHub to accept it) we use to create the AKS cluster here:
[azdeploy.txt](https://github.com/virtual-kubelet/azure-aci/files/5922459/azdeploy.txt)

You should be able to re-create the issue by running that in with appropriate parameters / variables. We are using a custom service principal for AKS, maybe this is the issue?

**Comment by feiskyer** [comment]
Probably because missing permissions. Have you assigned the required permissions, e.g. by running `az role assignment create --assignee $AZURE_CLIENT_ID --scope <vnetId> --role "Network Contributor"`?

**Comment by MattJeanes** [comment]
I have added that now with this command (slightly censored) and re-deployed it but unfortunately still the same error message. The client id is the same one AKS uses in the `servicePrincipalProfile` 

```
az role assignment create --assignee "cc0b9eb2-xxxx-xxxx-986b-d752078dc577" --scope "/subscriptions/6c5b0407-xxxx-xxxx-aa36-6293c5b35deb/resourceGroups/xxxxxx-aks-dev-weu-rg/providers/Microsoft.Network/virtualNetworks/xxxxxx-aks-dev-weu-vnet" --role "Network Contributor"
```

Perhaps I am missing some of the Helm parameters? Such as providers.azure.clientId/clientKey - I wasn't sure if those were required as it says you don't need them for AKS in the readme. Or maybe I need to follow the subnet creation steps and use a Helm command like this:

```
helm install "$RELEASE_NAME" "$CHART_URL" \
  --set provider=azure \
  --set providers.azure.targetAKS=true \
  --set providers.azure.vnet.enabled=true \
  --set providers.azure.vnet.subnetName=$ACI_SUBNET_NAME \
  --set providers.azure.vent.subnetCidr=$ACI_SUBNET_RANGE \
  --set providers.azure.vnet.clusterCidr=$CLUSTER_SUBNET_RANGE \
  --set providers.azure.vnet.kubeDnsIp=$KUBE_DNS_IP \
  --set providers.azure.masterUri=$MASTER_URI \
  --set nodeName=$NODE_NAME
```

**Comment by gossion** [comment]
@MattJeanes the error "Unauthorized, ok: false" means the request failed to call ACI request api, there is a known problem that AKS node checker failed to call /healthz check to virtual node, which does not matter for now.
We had just released https://github.com/virtual-kubelet/azure-aci/releases/tag/v1.3.3 which has enriched the Unauthorized logs, could you upgrade to that version and check the logs again?

**Comment by MattJeanes** [comment]
Okay, it looks like that version does not yet exist in the Helm charts - I will be happy to try this out once it's on there: https://github.com/virtual-kubelet/azure-aci/tree/master/charts

**Comment by MattJeanes** [comment]
So the logs on the new version now show this:

```
time="2021-02-19T02:10:53Z" level=info msg=Initialized node=virtual-kubelet-aci-win operatingSystem=Windows provider=azure watchedNamespace=
time="2021-02-19T02:10:53Z" level=info msg="Pod cache in-sync" node=virtual-kubelet-aci-win operatingSystem=Windows provider=azure watchedNamespace=
time="2021-02-19T02:10:53Z" level=info msg="starting workers" node=virtual-kubelet-aci-win operatingSystem=Windows provider=azure watchedNamespace=
time="2021-02-19T02:10:53Z" level=info msg="started workers" node=virtual-kubelet-aci-win operatingSystem=Windows provider=azure watchedNamespace=
time="2021-02-19T02:11:00Z" level=info msg="Unauthorized, ok: false, RequestURI:/healthz, UserAgent:aks-monitoring" node=virtual-kubelet-aci-win operatingSystem=Windows provider=azure watchedNamespace=
time="2021-02-19T02:11:06Z" level=info msg="Unauthorized, ok: false, RequestURI:/healthz, UserAgent:aks-monitoring" node=virtual-kubelet-aci-win operatingSystem=Windows provider=azure watchedNamespace=
time="2021-02-19T02:11:12Z" level=info msg="Unauthorized, ok: false, RequestURI:/healthz, UserAgent:aks-monitoring" node=virtual-kubelet-aci-win operatingSystem=Windows provider=azure watchedNamespace=
time="2021-02-19T02:11:18Z" level=info msg="Unauthorized, ok: false, RequestURI:/healthz, UserAgent:aks-monitoring" node=virtual-kubelet-aci-win operatingSystem=Windows provider=azure watchedNamespace=
time="2021-02-19T02:11:24Z" level=info msg="Unauthorized, ok: false, RequestURI:/healthz, UserAgent:aks-monitoring" node=virtual-kubelet-aci-win operatingSystem=Windows provider=azure watchedNamespace=
```

**Comment by feiskyer** [comment]
Thanks @MattJeanes for confirm. Those Unauthorized log could be safely omitted.

**Comment by MattJeanes** [comment]
Thanks, so it can be safely ignored? My only concern is that we and I imagine many other AKS users are logging console output and this message prints every 5 seconds which could get very expensive and use up a lot of storage.

**Comment by gossion** [comment]
yes, currently it can be ignored. We would find a way to remove those Unauthorized msg.
