### ISSUE TITLE
Pod Identity possible with sidecar? 

### ISSUE THREAD

**Issue by aidapsibr** [virtual-kubelet/azure-aci#131]
I was just reading the reason for closing #49 and it strikes me that if NMI was running as container within your pod, it should function on virtual kubelet.

Has this been attempted? We aren't yet running virtual kubelet, but it is in our plans later this year.

**Comment by feiskyer** [comment]
@ritazh @aramase is Pod Identity available running as a sidecar instead of a daemonset?

**Comment by matt-psaltis** [comment]
Any comment or new insights on this? We have an entire ecosystem built around managed identity and can't use virtual nodes due to this limitation.

**Comment by aramase** [comment]
Hello 👋🏻 

We're actively developing and testing AAD Pod Identity v2 internally. We will have an update soon on when the repository will be public. There is no NMI like component in v2, which means we no longer need host access for adding iptable rules. Once the v2 solution is available publicly we'll post in the aad-pod-identity repo.

>  is Pod Identity available running as a sidecar instead of a daemonset?

No, NMI can't be run as a sidecar as we try to apply the iptable rules on host to apply for every single pod.

**Comment by helayoty** [comment]
> Hello 👋🏻
> 
> We're actively developing and testing AAD Pod Identity v2 internally. We will have an update soon on when the repository will be public. There is no NMI like component in v2, which means we no longer need host access for adding iptable rules. Once the v2 solution is available publicly we'll post in the aad-pod-identity repo.
> 
> > is Pod Identity available running as a sidecar instead of a daemonset?
> 
> No, NMI can't be run as a sidecar as we try to apply the iptable rules on host to apply for every single pod.

@aramase @feiskyer What is the status of this issue?

**Comment by aramase** [comment]
> @aramase @feiskyer What is the status of this issue?

Please see announcement here: https://github.com/Azure/aad-pod-identity#aad-pod-identity. We're no longer making any feature changes in AAD Pod Identity. 

❗ IMPORTANT: As mentioned in the [announcement](https://cloudblogs.microsoft.com/opensource/2022/01/18/announcing-azure-active-directory-azure-ad-workload-identity-for-kubernetes/), we are planning to replace AAD Pod Identity with [Azure Workload Identity](https://azure.github.io/azure-workload-identity). Going forward, we will no longer add new features to this project in favor of Azure Workload Identity. However, we will continue patching critical bugs and security vulnerabilities until further notice.

I would recommend using [Azure Workload Identity](https://github.com/Azure/azure-workload-identity).

**Comment by helayoty** [comment]
@aidapsibr Closing the issue as per @aramase recommendation to use [Azure Workload Identity](https://github.com/Azure/azure-workload-identity) instead.
