### ISSUE TITLE
Upgrade to VK 1.5.0 and the dependency on node-cli

### ISSUE THREAD

**Issue by MikkelHegn** [virtual-kubelet/azure-aci#136]
The ACI provider currently runs 2 minor versions behind the virtual-kubelet library. [A lot of changes dating back to July 2020](https://github.com/virtual-kubelet/virtual-kubelet/compare/v1.3.0...v1.5.0). A quick look revealed the node-cli also needs updating from 1.3.0.

A spin-off question, not sure if this has been discussed before, but the node-cli repo states [that](https://github.com/virtual-kubelet/node-cli#virtual-kubelet-cli): 

> This project provides a library for rapid prototyping of a virtual-kubelet node. It is not intended for production use and may have breaking changes...

Should we bundle work to drop the dependency on the node-cli, or is the support statement not valid?

**Comment by cpuguy83** [comment]
I think it's worthwhile to get off of node-cli.
It is intended for getting a project off the ground, but causes problems for dependency management... it also masks the interfaces vk provides.

**Comment by MikkelHegn** [comment]
@feiskyer - just to confirm, this did not remove the dependency on the node-cli - correct?

**Comment by feiskyer** [comment]
no, it just upgraded the dependency.
