### ISSUE TITLE
The pods fails on ASK that uses a system-assigned Managed Identity

### ISSUE THREAD

**Issue by eugen-nw** [virtual-kubelet/azure-aci#143]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)

Version (e.g. 0.1, 0.2-beta)
latest

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS

Install Method (e.g. Helm Chart, )
Helm

### Repo Steps
1. I created the AKS instance in the Azure portal and picked to use a system-assigned Managed Identity

2. I installed the componentent using the command line: `helm install "$RELEASE_NAME" "$CHART_URL"  --set provider=azure  --set providers.azure.targetAKS=true  --set providers.azure.masterUri=$MASTER_URI  --set nodeName=$NODE_NAME  --set nodeOsType="Windows"`

3. I checked and the pod got into the CrashLoopBackOff status.  Its logs show:
```
time="2021-03-31T21:26:20Z" level=info msg="Using user identity for authentication"
time="2021-03-31T21:26:20Z" level=info msg=Initialized node=virtual-kubelet operatingSystem=Windows provider=azure watchedNamespace=
E0331 21:26:22.579413       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.4/tools/cache/reflector.go:125: Failed to list *v1.Service: the server is currently unable to handle the request (get services)
E0331 21:26:22.622565       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.4/tools/cache/reflector.go:125: Failed to list *v1.Secret: the server is currently unable to handle the request (get secrets)
E0331 21:26:22.622565       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.4/tools/cache/reflector.go:125: Failed to list *v1.Pod: the server is currently unable to handle the request (get pods)
E0331 21:26:22.622624       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.4/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: the server is currently unable to handle the request (get configmaps)
time="2021-03-31T21:26:22Z" level=fatal msg="the server is currently unable to handle the request (get nodes virtual-kubelet)" node=virtual-kubelet operatingSystem=Windows provider=azure watchedNamespace=
```

I was not able to find the reflector.go file in this repository to try to figure things out.  Please inform what AD roles do I need to assign to the Managed Identity in order to get the Virtual Kubelet working.

**Comment by feiskyer** [comment]
@eugen-nw could you assign the MSI with vnet contributor role?

**Comment by eugen-nw** [comment]
Thanks very much for your quick response!  Unfortunately, I could not get it to work, so the problem lies elsewhere.

This is what I did:

1. I called `az aks show -g myResourceGroup -n myManagedCluster --query "identity"` to retrieve the Managed Identity Principal's ID.

2. I used the Principal's ID in `az role assignment create --role` calls to set both `Contributor` and `Network Contributor` roles to both the `...-vnet` and `...-vnet/subnets/default`.  It did not work.

3. I used the Principal's ID in `az role assignment create --role` calls to set both `Contributor` both on the AKS cluster's resource group and on the `MC_...` resource group.  It still does not work.

**Comment by gossion** [comment]
It would have different error msg if it is permission issue, like:
```
time="2021-04-02T07:06:59Z" level=error msg="failed to retrive active container groups list" error="api call to https://management.azure.com/subscriptions/.../resourceGroups/.../providers/Microsoft.ContainerInstance/containerGroups?api-version=2018-10-01: got HTTP response status code 403 error code \"AuthorizationFailed\": The client '...' with object id '...' does not have authorization to perform action 'Microsoft.ContainerInstance/containerGroups/read' over scope '/subscriptions/.../resourceGroups/.../providers/Microsoft.ContainerInstance' or the scope is invalid. If access was recently granted, please refresh your credentials." method=PodsTracker.cleanupDanglingPods node=virtual-kubelet0402 operatingSystem=Linux provider=azure watchedNamespace=
```


> E0331 21:26:22.579413       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.4/tools/cache/reflector.go:125: Failed to list *v1.Service: the server is currently unable to handle the request (get services)
This error means that you are not able to connect to your apiserver or the apiserver can't response.  Please check the econnection first.

BTW, reflector.go  is not part of virtual-kubelet/azure-aci, it is standard k8s client-go, you can find it @ https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go

**Comment by eugen-nw** [comment]
Which apiserver please?

**Comment by gossion** [comment]
it is the 'kube-apiserver' pods managed by AKS. Inside of your virtual-kubelet-virtual-kubelet-aci-for-aks pod, it tried to resources (pods, secrets, nodes, etc) from the apiserver but it failed. It is hard to tell what was wrong from the log you provided, but it is very likely your  virtual-kubelet-virtual-kubelet-aci-for-aks pod can't talk to 'kube-apiserver'.

**Comment by eugen-nw** [comment]
Thanks very much for the info!  It was an experiment for me to set up the AKS cluster to use a Managed Identity.  I do not have the time to get it working, so I deleted the AKS instance and had created again using an SP I created beforehand.  The VK works now.

Have you guys tested the VK if it runs on AKS clusters that had been created to use an MI instance?  If yes and if it works consistently, then please feel free to close this ticket.

**Comment by feiskyer** [comment]
yes, VK works on AKS cluster with MI.

**Comment by helayoty** [comment]
@eugen-nw I believe this issue has been solved by now as AKS supports MI and VN has been working using MI for a year.

I'm going to close this issue for now. Please feel free to reopen it if the issue still happens with the latest release.
