### ISSUE TITLE
Readiness probe failes but pod is reported as ready

### ISSUE THREAD

**Issue by dhuesmann89** [virtual-kubelet/azure-aci#145]
I have deployed a helm package containing a pod with a readiness probe (httpGet). I know on the readme page it says, that its a limitation, but according to issue #12 it is not.
When I look at the container instance running in Azure, there are events that state that the readiness probe failed and the container is in an unhealthy state.
Kubernetes however shows the pod as ready and routes traffic to it.
Any ideas what could be going wrong here?

**Comment by helayoty** [comment]
This issue should be solved in the latest release. Please feel free to reopen the issue with logs if it's still happening.
