### ISSUE TITLE
Kubernetes status shows Waiting while ACI container is Running

### ISSUE THREAD

**Issue by asipras** [virtual-kubelet/azure-aci#146]
I am scheduling a Kubernetes Job on AKS which gets assigned to Virtual-Kublet aci. The job gets created correctly however when I run the kubectl get pods command I see the following,

![image](https://user-images.githubusercontent.com/16964799/120497532-1af07e00-c384-11eb-845a-8cabaa7d7676.png)

However when I go to Azure portal and see the container in virtual scale sets it shows it is already running.

![virtual_scale_sets](https://user-images.githubusercontent.com/16964799/120497758-4b381c80-c384-11eb-81f2-8f84684aa754.PNG)

I want to know why is the job status not in running state when query it using  kubectl get pods command. I also see the container is running but there is no workload running since the CPU/Memory/Network traffic is zero. 

Why is the workload not running if the container instance is in the running state?

**Comment by feiskyer** [comment]
could you check whether there're some error logs from virtual kubelet pod?

**Comment by helayoty** [comment]
@asipras Can you please provide more details? the pod spec, containers logs, k8s version

**Comment by helayoty** [comment]
Closing as there is no response from the author. @asipras please feel free to reopen it again with more details if still occurs.
