### ISSUE TITLE
Pods are slow to provision

### ISSUE THREAD

**Issue by ianadavies** [virtual-kubelet/azure-aci#151]
Can someone please let me know what is a typical time for a pod to provision onto a virtual node?

The smallest image i have is about 44MB and this takes ~60 seconds to provision, other images I have are up to 900MB and these take ~110 seconds to provision.

This is obviously much slower than using normal nodes.

I have noticed pods spend quite a lot of time in a "Waiting" state before they start running.

My use case is running simulations, as soon as messages hit a queue I spawn up a number of pods using KEDA, this is quite a bad user experience as it takes almost 2 minutes before the simulation starts running so any information or ideas on how I can improve the time would be appreciated.

NB: I have also tried different scale sets (higher performance nodes) and this does not seem to make any difference.

**Comment by ryanzhang-oss** [comment]
This is not really a virtual kubelet issue. The time to provision largely depends on the underlying container management platform.

**Comment by helayoty** [comment]
@ianadavies The starting time should be better now (~20-30 sec). Also, we are working on supporting scaling. I'll close this issue and kindly feel free to reopen it or report any other issues/features.
