### ISSUE TITLE
Pods deployed on Virtual node ends up in ProviderFailed status since AKS v1.21.0

### ISSUE THREAD

**Issue by asankaf** [virtual-kubelet/azure-aci#155]
Since Kubernetes 1.21.0, `RootCAConfigMap` is turned on by default which publishes a "kube-root-ca.crt" ConfigMap to every namespace, therefore instead of the service accounts, the pods are now mounted with a Projected volume. virtual-node-aci-linux v1.3.5 doesn't seem to support this type of volumes, thus the pods deployed in virtual node ends up in `ProviderFailed` status. Is there a fix or a workaround for this?

**Comment by feiskyer** [comment]
@asankaf Thanks for reporting the issue! It has been fixed and chart updated. Would you like to have a try?

**Comment by asankaf** [comment]
Hi,
Thanks for the fix. I'll try it out. I am guessing it will take some time to integrate this new release when the virtual node is enabled as an addon through az aks.

**Comment by asankaf** [comment]
Hi again,
I tested virtual-node-aci-linux 1.3.6 in our clusters and everything works just fine here. Thanks again for the fix it in a short notice.
