### ISSUE TITLE
"Network not ready" error

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/azure-aci#167]
When creating a pod it can end up in `ProviderFailed` state due to this error:

> api call to https://management.azure.com/subscriptions/[sub]/resourceGroups/MC_vk-aci-test-1635009878_vk-aci-test-1635009878_westus2/providers/Microsoft.ContainerInstance/containerGroups/default-nginx-67bf9cf5d-hdmqd?api-version=2018-10-01: got HTTP response status code 409 error code "ServiceAssociationLinkNotReady": Network is not ready for container group 'default-nginx-67bf9cf5d-hdmqd'. Please try again.

This is with vnet enabled.

This requires manual intervention to delete the pod so the deployment controller can create a new one.

I suppose it would be nice if ACI handled this itself w/o involving the client, but we could try recreating the containers from VK if we receive this error.

**Comment by helayoty** [comment]
This should be fixed by release 1.4.16, as we introduced an init container to make sure all network configurations are in place before staring the virtual node.
