### ISSUE TITLE
Control Characters are not allowed

### ISSUE THREAD

**Issue by steephan-s1** [virtual-kubelet/azure-aci#179]
Hi,

When i run this command <helm install analytics ./analytics_chart/>
Im getting this error (Error: INSTALLATION FAILED: YAML parse error on insight/templates/20.InsightDataService/.vs/20.InsightDataService/v16/.suo: error converting YAML to JSON: yaml: control characters are not allowed).
Can you please guide me to fix this issue.

**Comment by ryanzhang-oss** [comment]
Hi, can you paste your exact command and error here?
