### ISSUE TITLE
support for initContainers

### ISSUE THREAD

**Issue by ptemmer** [virtual-kubelet/azure-aci#18]
It would be very nice if ACI supported initContainers, as many of the most basic deployments rely on initContainer(s) to work.

Also see https://github.com/Azure/AKS/issues/1155

**Comment by macolso** [comment]
Thanks for the suggestion! Good news - support for initContainers is already on our roadmap.

**Comment by sebastianhutter** [comment]
@macolso any news on the initcontainers support? it would help us quite a bit.

**Comment by ktumu0225** [comment]
Any updates on this yet? We are eagerly waiting for this feature as we can run a lot of our workloads that needs init containers hosted in AKS on Virtual Nodes.

**Comment by zhoufenqin** [comment]
+1, do you have the ETA for the feature? We need to use this feature to support our works.

**Comment by helayoty** [comment]
The feature will be ready in Release `1.5` 
#204
