### ISSUE TITLE
Clarify Azure Files support for volumes

### ISSUE THREAD

**Issue by letmaik** [virtual-kubelet/azure-aci#181]
https://docs.microsoft.com/en-us/azure/aks/virtual-nodes says in Limitations:
> Volume mounting Azure Files share support General-purpose V1. Follow the instructions for mounting a volume with Azure Files share

If I understand correctly, then this means V2 is not supported. Is that accurate? I couldn't find the same limitation listed in https://github.com/virtual-kubelet/azure-aci/blob/master/README.md#limitations

**Comment by helayoty** [comment]
@letmaik Thanks for reaching out.  Storage V2 is supported when using `virtual-kubelet/azure-aci`. Please let us know if you encounter any issues with that.
