### ISSUE TITLE
support out of tree csi azure disk storage class

### ISSUE THREAD

**Issue by ryanzhang-oss** [virtual-kubelet/azure-aci#182]
Azure-aci only supports in-tree storage classes.  We need to add support for out-of-tree storage class.

We need to fix that before 1.26 (which will remove in-tree storage support).

**Comment by ryanzhang-oss** [comment]
code the change should be around 
https://github.com/virtual-kubelet/azure-aci/blob/master/provider/aci.go#L1635

**Comment by ryanzhang-oss** [comment]
We also need an e2e test  in the aks-rp repo

test/e2e/suites/virtualnodeaddon

**Comment by helayoty** [comment]
duplicate
