### ISSUE TITLE
Incorrect documentation for installation of ACI provider

### ISSUE THREAD

**Issue by anupbarve** [virtual-kubelet/azure-aci#190]
The README provides following way of fetching the MASTER_URI.

export MASTER_URI="$(kubectl cluster-info | awk '/Kubernetes control plane/{print $7}' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")"

For my AKS cluster, the above command gives the MASTER_URI as "https://vkubeletak-vkubelet-****.hcp.westus.azmk8s.io:443"

Using this URI during helm install gives following error while creating the pod

time="2022-03-10T11:23:01Z" level=fatal msg="parse \"https://\\x1b[0;33mhttps://vkubeletak-vkubelet-576a4e-8277f36d.hcp.westus.azmk8s.io:443\\x1b[0m\": net/url: invalid control character in URL"

I had to remove the port and "https" from the URI to get it working.

**Comment by helayoty** [comment]
> export MASTER_URI="$(kubectl cluster-info | awk '/Kubernetes control plane/{print $7}' | sed "s,\x1B[[0-9;]*[a-zA-Z],,g")"
> 
@anupbarve 
It seems the command above is missing`\` after`\x1B`.

Please try the following:
`export MASTER_URI="$(kubectl cluster-info | awk '/Kubernetes control plane/{print $7}' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")"`
