### ISSUE TITLE
beta.kubernetes.io/os deprecated

### ISSUE THREAD

**Issue by ModernRonin** [virtual-kubelet/azure-aci#201]
Hi,

when using the nodeSelector with `beta.kubernetes.io/os`, AKS/k8 complains:

> Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead

[Microsoft's documentation](https://docs.microsoft.com/en-us/azure/aks/use-labels#deprecated-labels) also states that the beta version of the label is scheduled for removal by 1.24.

Is this on your radar? 
And how does this play with updates: eventually, we will have to update the kubelet to a newer version. But if the virtual-node support was added upon creation of the AKS cluster via the Azure portal, then how would we go about that? Or is this happening automatically?

**Comment by mmontesi** [comment]
Same concern here.
As @ModernRonin said 1.24 it's not so far away...
Maybe we could label the virtual node with the new annotation and accordingly update the nodeSelector in our deployments, but I'd like an out-of-the-box solution.
Is that planned?
