### ISSUE TITLE
virtual-kubelet helm install for AKS with user managed identity results in virtual-kubelet pod restarting with identity not found error

### ISSUE THREAD

**Issue by aneran01** [virtual-kubelet/azure-aci#202]
### virtual-kubelet helm install for AKS with user managed identity results in virtual-kubelet pod restarting with identity not found error

We are trying to deploy virtual-kubelet helm package on AKS cluster to provision virtual node and test out scaling on same.
Doing same using terraform with aci_connector_linux does work smooth after assigning roles to the user managed identity which gets created during AKS cluster creation as below.

```
aci_connector_linux {
    subnet_name = "${azurerm_subnet.aci.name}"
  }
```

```
data "azurerm_user_assigned_identity" "aks-aci_identity" {
  name = "aciconnectorlinux-${azurerm_kubernetes_cluster.main.name}"
  resource_group_name = "MC_${local.name_prefix}-resources_${local.name_prefix}-cluster_${azurerm_resource_group.main.location}"
  depends_on   = [azurerm_kubernetes_cluster.main]
}

# Grant user_assigned_identity contributor permission to the RG, specifically the AKS rg
resource "azurerm_role_assignment" "aci_identity_rg" {
  principal_id         = data.azurerm_user_assigned_identity.aks-aci_identity.principal_id
  role_definition_name = "Contributor"
  scope                = "${azurerm_resource_group.main.id}"
}

resource "azurerm_role_assignment" "aks-aci-vnet-assignment" {
  scope                = "${azurerm_virtual_network.main.id}"
  role_definition_name = "Reader"
  principal_id         = data.azurerm_user_assigned_identity.aks-aci_identity.principal_id
}

resource "azurerm_role_assignment" "aks-aci-subnet-assignment" {
  scope                = "${azurerm_subnet.aci.id}"
  role_definition_name = "Network Contributor"
  principal_id         = data.azurerm_user_assigned_identity.aks-aci_identity.principal_id
}
```

But the same fails when we try to enable virtual-kubelet using helm package as described below:

**Note:** We cannot use service principals in our setup as it is forbidden for us and recommended to keep least usage of same.

**Steps to Reproduce:**

granted below roles to the user managed identity via terraform which will be used while installing helm package of virtual-kubelet,

```
resource "azurerm_user_assigned_identity" "aks-aci_identity" {
  name                = "aciconnectorlinux-${local.aks1.cluster_name}"
  resource_group_name = module.aks1_resource_group_eastus.name
  location            = module.aks1_resource_group_eastus.location
}

# Grant user_assigned_identity contributor permission to the RG, specifically the AKS rg
resource "azurerm_role_assignment" "aci_identity_rg" {
  principal_id         = azurerm_user_assigned_identity.aks-aci_identity.principal_id
  role_definition_name = "Contributor"
  scope                = module.aks1_resource_group_eastus.id
}

resource "azurerm_role_assignment" "vnet_rg" {
  principal_id         = azurerm_user_assigned_identity.aks-aci_identity.principal_id
  role_definition_name = "Contributor"
  scope                = module.resource_group_eastus.id
}

resource "azurerm_role_assignment" "aks-aci-vnet-assignment" {
  scope                = module.virtual_network.vnet.id
  role_definition_name = "Reader"
  principal_id         = azurerm_user_assigned_identity.aks-aci_identity.principal_id
}

resource "azurerm_role_assignment" "aks-aci-subnet-assignment" {
  scope                = module.virtual_network.subnets["service-subnet2"].id
  role_definition_name = "Network Contributor"
  principal_id         = azurerm_user_assigned_identity.aks-aci_identity.principal_id
}
```

**AKS cluster with Vnet:**

```
export RELEASE_NAME=virtual-kubelet
export VK_RELEASE=virtual-kubelet-latest
export CHART_URL=https://github.com/virtual-kubelet/azure-aci/raw/master/charts/$VK_RELEASE.tgz
export MASTER_URI="$(kubectl cluster-info | awk '/Kubernetes control plane/{print $7}' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")"

IDENTITY_MANAGED_ID="8a4596b6-06e7-4a5a-a9a1-6f1d5dd4e11d"  # passed client id of user managed identity
KUBE_DNS_IP="172.20.0.10"
ACI_SUBNET_NAME="service-subnet2"
ACI_SUBNET_RANGE="10.228.167.32/27"
CLUSTER_SUBNET_RANGE="10.228.166.0/23"
NODE_NAME="node-01"
```

helm install "$RELEASE_NAME" "$CHART_URL" \
  --set provider=azure \
  --set providers.azure.targetAKS=true \
  --set providers.azure.managedIdentityID=$IDENTITY_MANAGED_ID \  # passed user managed identity client id
  --set providers.azure.vnet.enabled=true \
  --set providers.azure.vnet.subnetName=$ACI_SUBNET_NAME \
  --set providers.azure.vent.subnetCidr=$ACI_SUBNET_RANGE \
  --set providers.azure.vnet.clusterCidr=$CLUSTER_SUBNET_RANGE \
  --set providers.azure.vnet.kubeDnsIp=$KUBE_DNS_IP \
  --set providers.azure.masterUri=$MASTER_URI \
  --set nodeName=$NODE_NAME 

The virtual kubelet pod fails to start and gives below errors in log:

time="2022-05-23T08:49:04Z" level=info msg="Using user identity for authentication"
time="2022-05-23T08:49:04Z" level=error msg="Unable to fetch the ACI metadata, skipping GPU availability check. GPU capacity will be disabled" error="Sending get resource provider manifest request failed: Get \"https://management.azure.com/providers/Microsoft.ContainerInstance?%24expand=metadata&api-version=2018-02-01\": Failed to refresh the authorization token for request to https://management.azure.com/providers/Microsoft.ContainerInstance?%24expand=metadata&api-version=2018-02-01: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"}" method=setupCapacity
Error: error initializing provider azure: error setting up network: error while looking up subnet: sending subnet get request failed: Get "https://management.azure.com/subscriptions/32496c5b-1147-452c-8469-3a11028f8946/resourcegroups/app-tfe-dev-eastus/providers/Microsoft.Network/virtualNetworks/core-dev-eastus-vnet/subnets/service-subnet2?api-version=2018-08-01": Failed to refresh the authorization token for request to https://management.azure.com/subscriptions/32496c5b-1147-452c-8469-3a11028f8946/resourcegroups/app-tfe-dev-eastus/providers/Microsoft.Network/virtualNetworks/core-dev-eastus-vnet/subnets/service-subnet2?api-version=2018-08-01: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}

Am I missing something? Why is it not able to identify the identity and send subnet get request?
Please suggest.

**Comment by helayoty** [comment]
@aneran01  would you please verify if this issue was solved in the last release or not?
