### ISSUE TITLE
how to mount configmap / secret to a pod running in ACI from AKS 

### ISSUE THREAD

**Issue by xinity** [virtual-kubelet/azure-aci#243]
hello,

been validating using Azure ACI to burst my AKS worloads.
While i can easily scale my pods on my AKS nodes without issues, those pods can't be started the moment i'm adding some configmaps.

tried to remove them and the pods starts perfectly on both AKS and ACI, if i re-enable them, pods will only start on my AKS nodes.

is there any specific configuration to make it work on both with configmap ?
how about kubernetes secret does it work the same ?

**Comment by helayoty** [comment]
Hey @xinity , the current way to be able to read configmaps while using `Virtual-Kubele`/`azure-aci` is to mount the configmap as a volume. 

ref: https://github.com/virtual-kubelet/azure-aci/blob/master/provider/aci.go#L1777
