### ISSUE TITLE
Add support for using MSI to authenticate

### ISSUE THREAD

**Issue by norshtein** [virtual-kubelet/azure-aci#3]
Seems currently the virtual kubelet [can only use service principal to authenticate](https://github.com/virtual-kubelet/azure-aci/blob/20574686f4a23a4064640cd6053db85b658e1395/acsCredential.go#L13), can we support using MSI to authenticate?

**Comment by macolso** [comment]
Currently we can only authenticate using service principals with Virtual Kubelet. We're working on bringing MSI support to ACI today. When that work lands, we'll work on integrating it with Virtual Kubelet as well.

**Comment by gossion** [comment]
this is supported now. closing the issue.
