### ISSUE TITLE
It'd be nice to document that the secret expires after a year

### ISSUE THREAD

**Issue by eugen-nw** [virtual-kubelet/azure-aci#30]
Or even better, to document how to update the certificate ;-)

I've noticed yesterday that the containers I deployed onto the Virtual Kubelet were going into the ProviderFailed STATUS, with an error message along the lines of "Sending create container group request failed: Put https://management.azure.com/subscriptions... AADSTS7000222: The provided client secret keys are expired..." error message.

Since the AKS' and other Azure Service Principals were OK, I called "kubectl describe secret aci-connector-windows-windows-westus-virtual-kubelet-for-aks" and it sure showed some certificate type of a secret.  As I were guessing that it may have expired, I ran "az aks remove-connector..." followed by "az aks install-connector..." and everything worked correctly afterwards.

**Comment by ibabou** [comment]
@eugen-nw thanks for reporting this! Is there a reason for not using addon ? it gets refreshed automatically by AKS team, as part of addons updates. in this case, you probably won't his this issue, in addition to having the auto updates. Add-on can be added/removed through az aks (enable/disable)-addons --addons virtual-node.

**Comment by eugen-nw** [comment]
Thanks very much for the info!  I'm new to AKS & K8S, so I've never heard of any addons.  I'll install the virtual-node one.  Could someone please add this piece of information to the https://github.com/virtual-kubelet/azure-aci as chances are that this issue will trip someone else as well.

What do you mean with "having the auto updates", please?  What exactly will be updated automatically?

**Comment by eugen-nw** [comment]
I do not understand this very well.  I thought that the ACI connector pod is creating virtual nodes by delegating the running of the containers to the ACI instance.  Why do I need to configure the AKS instance as well to support virtual nodes please?

**Comment by macolso** [comment]
Hey @eugen-nw! Thanks for the catch - we'll update the documentation here. 

_What do you mean with "having the auto updates", please?_ Whenever we push new changes to the ACI provider, it gets automatically updates via the AKS Virtual Node add on. This includes new features, bug fixes, etc. It will also auto-refresh the certificate that went stale on you.

_Why do I need to configure the AKS instance as well to support virtual notes?_ Virtual nodes was created as an abstraction for AKS users. At the end of the day, the fact that the Virtual nodes are implemented as Azure Container Instances is an abstraction detail. The Virtual node user experience is support to target AKS users who want to provision "serverless" nodes. Does this make sense?

**Comment by eugen-nw** [comment]
For my own education please: for what does the ACI connector use that certificate-type secret that expires after a year?
