### ISSUE TITLE
AKS virtual node monitor

### ISSUE THREAD

**Issue by ayelencasamassa** [virtual-kubelet/azure-aci#347]
**Describe the Issue**
Pods created on virtual node don't report logs to Monitor

**Steps To Reproduce**
AKS with virtual nodes 

**Expected behavior**
Check logs on WorkSpace (Azure Monitor)

**Virtual-kubelet version**
latest

**azure-aci plugin version**
latest

**Kubernetes version**
latest

**Additional context**
Using Terraform as IaC

**Comment by helayoty** [comment]
@ayelencasamassa Can you please confirm if this issue still happening in the release `v1.4.6`? If yes, would you please add the details in the issue description?

**Comment by ayelencasamassa** [comment]
@helayoty Seems like logs for ACI are stored in a different table, a custom table on Log Analytics Workspace. By default, AKS is checking in non-ACI log table. 
Do you know if this will fix soon?

**Comment by helayoty** [comment]
> @helayoty Seems like logs for ACI are stored in a different table, a custom table on Log Analytics Workspace. By default, AKS is checking in non-ACI log table. Do you know if this will fix soon?

Kindly provide the following information to be able to do more investigation:

**Describe the Issue**

**Steps To Reproduce**

**Expected behavior**

**Virtual-kubelet version**

**azure-aci plugin version**

**Kubernetes version**

**Comment by ayelencasamassa** [comment]
**Describe the Issue**
Pods created on virtual node don't report logs on AKS since those logs are stored in a custom table

**Steps To Reproduce**
AKS with virtual nodes

**Expected behavior**
See logs when I access with AKS GUI

**Virtual-kubelet version**
1.4.5

**azure-aci plugin version**
?

**Kubernetes version**
1.24.6

**Comment by helayoty** [comment]
Please let us know if you still face this issue with the release `1.4.7`.
