### ISSUE TITLE
How can I find out the connector's name?

### ISSUE THREAD

**Issue by eugen-nw** [virtual-kubelet/azure-aci#35]
I have a completely rookie question please.  I installed the previous Windows ACI connector using the "az aks install-connector ..." command.  Now I try to remove it using the "az aks remove-connector ..." command but do not know what value to pass for the --connector-name parameter.

Thank you,  eugen

**Comment by macolso** [comment]
```aci-connector```

**Comment by macolso** [comment]
For reference: https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-remove-connector

**Comment by eugen-nw** [comment]
Thanks very much @macolso!  Unfortunately, it does not seem to work.  It does not complain, but does not remove it either:

![image](https://user-images.githubusercontent.com/15199814/72567888-ab9bec00-386b-11ea-8c47-373652f3c6a8.png)

**Comment by macolso** [comment]
Strange. Out of curiosity, when did you add the connector?

**Comment by eugen-nw** [comment]
The aci-connector-windows-eastus-virtual-kubelet-for-aks-6b54777vg9 says that its age is 68d.  I remember that it was early Nov.
