### ISSUE TITLE
Multiple Node Pools on AKS - Virtual Kublet association.

### ISSUE THREAD

**Issue by fisapras** [virtual-kubelet/azure-aci#36]
If Virtual Kublet is enabled on AKS with multiple node pools, at the time of node scaling which node pool configuration is used to scale. Is it the default node pool configuration the one that gets created first when AKS resource is created?

Is there a way to configure Virtual Kubelet so that we can specify which node pool to use for scaling?

**Comment by ibabou** [comment]
@fisapras Sorry for the delayed response. Can you please clarify more about the scenario you're trying to achieve ?

VN works independently of agentpools that is actual VM resources representing the worker nodes. If a pod has tolerations to run on VN, then scheduler can pick VN and assign to it -- then the pod will be deployed on an external Serverless provider. On the other hand, the cluster autoscaler scales only the regular agentpools, it waits to see if there is unscheduled pods (failed to schedule) that matches an agentpool, then scales its number of VMs (so an already scheduled pod to VN, won't cause any trigger for this autoscaler).
