### ISSUE TITLE
AKS with virtual nodes is not working

### ISSUE THREAD

**Issue by ayelencasamassa** [virtual-kubelet/azure-aci#372]
**Describe the Issue**
I have created an AKS cluster with virtual nodes addon enabled but the node is never created and pods can't be scheluded

**Steps To Reproduce**
Create an AKS cluster with virtual nodes enabled

**Expected behavior**
Can check the virtual node

**Virtual-kubelet version**
latest

**azure-aci plugin version**
latest

**Kubernetes version**
1.24.6

**Additional context**
No

**Comment by ayelencasamassa** [comment]
MS creates the cluster with version 1.4.6 by default... seems like that version is not working.
I forced version 1.4.7 and, at least, now i can see the virtual node.
I didn't test it yet but I need to solve the problem with versions.
When version 1.4.7 will be released to MS?

**Comment by helayoty** [comment]
@ayelencasamassa  Thanks for reporting the issue, the issue should be fixed in the latest version 1.4.7, it will take a while till this change is rolled out to all regions. To unblock you, kindly follow the [downgrade](https://github.com/virtual-kubelet/azure-aci/blob/master/docs/DOWNGRADE-README.md) document.

**Comment by ayelencasamassa** [comment]
> @ayelencasamassa Thanks for reporting the issue, the issue should be fixed in the latest version 1.4.7, it will take a while (week/2 weeks) till this change is rolled out to all regions. To unblock you, kindly follow the [downgrade](https://github.com/virtual-kubelet/azure-aci/blob/master/docs/DOWNGRADE-README.md) document.

Heba, version 1.4.5 can't be deployed. It fails. 
The only option now is forcing v.1.4.7 by Helm.
How is the process of releasing a new version? Is there any kind of notification?
This is the second time I have issues with this (v1.4.4 and now 1.4.6) and my cluster was seriously affected.

**Comment by ayelencasamassa** [comment]
Any news about this?
Versions 1.4.5, 1.4.6 and 1.4.7 are not working.

**Comment by helayoty** [comment]
> Any news about this? Versions 1.4.5, 1.4.6 and 1.4.7 are not working.

May I know the issue you're facing by using `1.4.7`?

**Comment by ayelencasamassa** [comment]
Same as version 6, pods are not scheduled. 
An IP is not being assigned and the services shows service endpoint error.

**Comment by helayoty** [comment]
> 

Would you please share more logs?

**Comment by ayelencasamassa** [comment]
![image](https://user-images.githubusercontent.com/80763217/203829920-5dc36fe4-83f8-4e1f-89d9-bfca842fb0a0.png)

this is the command i used to deploy:

helm install "virtual-kubelet" "https://github.com/virtual-kubelet/azure-aci/raw/gh-pages/charts/virtual-kubelet-azure-aci-1.4.7.tgz" 
--set provider=azure 
--set rbac.install=true 
--set providers.azure.targetAKS=false 
--set providers.azure.aciResourceGroup=*** 
--set providers.azure.aciRegion=*** 
--set providers.azure.tenantId=*** 
--set providers.azure.subscriptionId=*** 
--set providers.azure.clientId=*** 
--set providers.azure.clientKey=*** 
--set providers.azure.masterUri=*** 
--set nodeName=virtual-kubelet 
--set providers.azure.vnet.subnetName=*** 
--set providers.azure.vent.subnetCidr=*** 
--set providers.azure.vnet.clusterCidr=*** 
--set providers.azure.vnet.kubeDnsIp=***

I modified the command you have documented because:
1- the chart name is wrong in the doc
2- it doesn't create the MI correctly
3- it can't access to the subnet

This is the command that works for me but i can't schedule pods

**Comment by ayelencasamassa** [comment]
can we put some priority here? tomorrow will be a week since our services went down

**Comment by helayoty** [comment]
hotfix has been rolled out to the affected region.

**Comment by ayelencasamassa** [comment]
it working now but what about the future? what is the release management policy? it was a week until i have my system back to live.

**Comment by helayoty** [comment]
> it working now but what about the future? what is the release management policy? it was a week until i have my system back to live.

Thanks for being patient and cooperative while we were upgrading the whole service to have better performance and getting it ready for more features. we apologize for any inconvenience and hope that won't happen in the future.

**Comment by ayelencasamassa** [comment]
I have been testing the solution.
Seems like communication between pods in virtual nodes is not working.
I have PodA that is trying to access PodB (that contains a redis db).
I have this error: Error: Redis connection to ***.***.svc.cluster.local:6379 failed - getaddrinfo ENOTFOUND ***.***.svc.cluster.local
I set exactly the same pods on a node-pool (VMSS - linux) and it works as expected.

Please, reopen this ticket
