### ISSUE TITLE
helm v3.3.4 cannot install

### ISSUE THREAD

**Issue by eugen-nw** [virtual-kubelet/azure-aci#374]
I'm trying to install the Windows VK using the `helm install "$RELEASE_NAME" "$CHART_URL"  --set provider=azure  --set providers.azure.targetAKS=true  --set providers.azure.masterUri=$MASTER_URI  --set nodeName=$NODE_NAME  --set nodeOsType="Windows"` command => `Error: failed to download "https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-latest.tgz" (hint: running `helm repo update` may help)`

`helm repo update` says that there are no repositories.

Could anyone please instruct how do I set up a helm repository so I can install the VK?

**Comment by helayoty** [comment]
@eugen-nw did you try to follow [this](https://github.com/virtual-kubelet/azure-aci/tree/master/charts/virtual-kubelet) document?

**Comment by eugen-nw** [comment]
Thanks very much, I found it myself and it did work.  However, could someone please update this document: https://github.com/virtual-kubelet/azure-aci/blob/master/README.md
