### ISSUE TITLE
After down-scale operations, VK leaves containers running in Azure ACI

### ISSUE THREAD

**Issue by eugen-nw** [virtual-kubelet/azure-aci#378]
**Describe the Issue**
I noticed that after I use kubectl to remove Pods, `kubectl get pods` no longer shows them, but Azure ACI in the Portal shows them still up and running.  That is really wasteful because it causes us to pay for running the Containers that we already decided that we do not need.  It will be quite costly for us in the long run because we use HPA for auto scaling operations.

**Steps To Reproduce**
Run either of the commands below and notice the behavior:
`kubectl scale deployment <deployment name>  --replicas=2` going down from 4 replicas
`kubectl delete pod <pod name`

**Expected behavior**
Pods that I no longer see when I run `kubectl get pods` should get removed from ACI as well

Virtual-kubelet version
helm-chart/aks/virtual-kubelet-azure-aci/1.4.7

azure-aci plugin version
Not certain what is this or how to obtain the information.

Kubernetes version
AKS 1.21.9

Additional context
I've used the VK since at least 2019 but had never had this experience.

**Comment by helayoty** [comment]
@eugen-nw  Thanks for reaching out, we cannot reproduce this issue from our end and we can see the ACI instance got deleted once you delete the pod or downscale the deployment. 

Kindly, can you share with us the steps to reproduce this issue and virtual kubelet logs? You can upload the required info to https://gist.github.com/ and share the link with us.

**Comment by eugen-nw** [comment]
Please see the image below for the repro.  I checked ACI afterwards and 6 instances of "default-aks-aci-boldiq-workforce-gozen-..." were present, neither of them in a "Terminating" state.  I had to manually delete 4 of them.
![image](https://user-images.githubusercontent.com/15199814/204630616-2def8ad2-9cc3-4439-8574-eba41e45a9e1.png)

The VK.log below I generated right after running the operations above. 
[VK.zip](https://github.com/virtual-kubelet/azure-aci/files/10116692/VK.zip)

**Comment by eugen-nw** [comment]
This is the exact information of the VK Pod:
```
PS C:\projects> kdp virtual-kubelet-azure-aci-virtual-kubelet-azure-aci-5969cfh968w
Name:         virtual-kubelet-azure-aci-virtual-kubelet-azure-aci-5969cfh968w
Namespace:    default
Priority:     0
Node:         aks-agentpool-30560331-vmss000000/10.240.0.4
Start Time:   Mon, 28 Nov 2022 11:54:16 -0800
Labels:       app=virtual-kubelet-azure-aci-virtual-kubelet-azure-aci
              pod-template-hash=5969cf667f
Annotations:  checksum/secret: 9b5e42fad3b27257d94ce60776569ec96cf5d6847a927aafb7e1bccb48a9bebe
Status:       Running
IP:           10.240.0.112
IPs:
  IP:           10.240.0.112
Controlled By:  ReplicaSet/virtual-kubelet-azure-aci-virtual-kubelet-azure-aci-5969cf667f
Containers:
  virtual-kubelet-azure-aci-virtual-kubelet-azure-aci:
    Container ID:  containerd://6c7fb3a4e0d37185c5c42943a05f6f7408b9196dcbd239ff7040ecb61ba196b3
    Image:         mcr.microsoft.com/oss/virtual-kubelet/virtual-kubelet:1.4.7
    Image ID:      mcr.microsoft.com/oss/virtual-kubelet/virtual-kubelet@sha256:dabe1be5103fbf6ae996b80b8daaca2b5a47726e32a73c761d3ec6824752538d
    Port:          <none>
    Host Port:     <none>
    Command:
      virtual-kubelet
    Args:
      --provider
      azure
      --namespace

      --nodename
      virtual-kubelet
      --authentication-token-webhook=true
      --client-verify-ca
      /etc/kubernetes/certs/ca.crt
      --no-verify-clients=false
      --os
      Windows
    State:          Running
      Started:      Mon, 28 Nov 2022 11:54:18 -0800
    Ready:          True
    Restart Count:  0
    Environment:
      KUBELET_PORT:              10250
      APISERVER_CERT_LOCATION:   /etc/virtual-kubelet/cert.pem
      APISERVER_KEY_LOCATION:    /etc/virtual-kubelet/key.pem
      VKUBELET_POD_IP:            (v1:status.podIP)
      VKUBELET_TAINT_KEY:        virtual-kubelet.io/provider
      VKUBELET_TAINT_VALUE:      azure
      VKUBELET_TAINT_EFFECT:     NoSchedule
      AKS_CREDENTIAL_LOCATION:   /etc/aks/azure.json
      AZURE_TENANT_ID:
      AZURE_SUBSCRIPTION_ID:
      AZURE_CLIENT_ID:
      AZURE_CLIENT_SECRET:       <set to the key 'clientSecret' in secret 'virtual-kubelet-azure-aci-virtual-kubelet-azure-aci'>  Optional: false
      ACI_RESOURCE_GROUP:
      ACI_REGION:
      ACI_EXTRA_USER_AGENT:      helm-chart/aks/virtual-kubelet-azure-aci/1.4.7
      MASTER_URI:                https://aks-workforce-dns-fe064e62.hcp.westus.azmk8s.io:443
      ENABLE_REAL_TIME_METRICS:  true
      USE_VK_VERSION_2:          true
    Mounts:
      /etc/aks/azure.json from aks-credential (rw)
      /etc/kubernetes/certs from certificates (ro)
      /etc/virtual-kubelet from credentials (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vh2zn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  virtual-kubelet-azure-aci-virtual-kubelet-azure-aci
    Optional:    false
  certificates:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/certs
    HostPathType:
  aks-credential:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  kube-api-access-vh2zn:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              beta.kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute for 300s
                             node.kubernetes.io/unreachable:NoExecute for 300s
Events:                      <none>```

**Comment by eugen-nw** [comment]
Please find the vk.log file in this Gist: https://gist.github.com/eugen-nw/fd4526514a4ab6c3b9d995b0e76e9475  It should have 50478 lines.

**Comment by uveta** [comment]
We have probably encountered a similar problem. Currently using VK 1.4.8., and one of our services, which is scaling out to ACI, is not deleting ACI instances after pod is removed. I extracted pod logs for this specific instance https://gist.github.com/uveta/cade31a76b5c202a1725f538925219a5

We have other services in the same AKS cluster, that are scaling out to ACI as well, and they seem to behave fine, i.e. ACI is not left running after pods are removed.

**Comment by helayoty** [comment]
> We have probably encountered a similar problem. Currently using VK 1.4.7., and one of our services, which is scaling out to ACI, is not deleting ACI instances after pod is removed. I extracted pod logs for this specific instance https://gist.github.com/uveta/cade31a76b5c202a1725f538925219a5
> 
> We have other services in the same AKS cluster, that are scaling out to ACI as well, and they seem to behave fine, i.e. ACI is not left running after pods are removed.

@uveta thanks for reaching out. The `1.4.8` is not released yet. Kindly roll back to `1.4.5` as a quick mitigation for this issue. A [downgrade](https://github.com/virtual-kubelet/azure-aci/blob/master/docs/DOWNGRADE-README.md) document should help you in this process.

**Comment by eugen-nw** [comment]
This problem is caused by 1.4.7 having the issue I described in #377

After I replaced the installed VK with 1.4.2, I no longer experience the behavior described in this ticket.

**Comment by eugen-nw** [comment]
It's not fair to close this issue because it is present in 1.4.7 and needs to be addressed.

**Comment by uveta** [comment]
> > We have probably encountered a similar problem. Currently using VK 1.4.7., and one of our services, which is scaling out to ACI, is not deleting ACI instances after pod is removed. I extracted pod logs for this specific instance https://gist.github.com/uveta/cade31a76b5c202a1725f538925219a5
> > We have other services in the same AKS cluster, that are scaling out to ACI as well, and they seem to behave fine, i.e. ACI is not left running after pods are removed.
> 
> @uveta thanks for reaching out. The `1.4.8` is not released yet. Kindly roll back to `1.4.5` as a quick mitigation for this issue. A [downgrade](https://github.com/virtual-kubelet/azure-aci/blob/master/docs/DOWNGRADE-README.md) document should help you in this process.

@helayoty thank you for the suggestion. We have actually tried rolling back to 1.4.6. and 1.4.5., and so far, 1.4.6. seems to be the most stable one out of all three versions. What is raising my concern is this line, that is often found in the logs I shared:

`error="container web-3d-viewer properties CurrentState StartTime cannot be nil"`

Also one thing to note, the image, that is causing problems, takes longer time to startup in ACI, even up to 10 minutes. Other service images are usually up and running within 1-2 minutes. Could this present an issue for azure aci kubelet?

**Comment by helayoty** [comment]
> > > We have probably encountered a similar problem. Currently using VK 1.4.7., and one of our services, which is scaling out to ACI, is not deleting ACI instances after pod is removed. I extracted pod logs for this specific instance https://gist.github.com/uveta/cade31a76b5c202a1725f538925219a5
> > > We have other services in the same AKS cluster, that are scaling out to ACI as well, and they seem to behave fine, i.e. ACI is not left running after pods are removed.
> > 
> > 
> > @uveta thanks for reaching out. The `1.4.8` is not released yet. Kindly roll back to `1.4.5` as a quick mitigation for this issue. A [downgrade](https://github.com/virtual-kubelet/azure-aci/blob/master/docs/DOWNGRADE-README.md) document should help you in this process.
> 
> @helayoty thank you for the suggestion. We have actually tried rolling back to 1.4.6. and 1.4.5., and so far, 1.4.6. seems to be the most stable one out of all three versions. What is raising my concern is this line, that is often found in the logs I shared:
> 
> `error="container web-3d-viewer properties CurrentState StartTime cannot be nil"`
> 
> Also one thing to note, the image, that is causing problems, takes longer time to startup in ACI, even up to 10 minutes. Other service images are usually up and running within 1-2 minutes. Could this present an issue for azure aci kubelet?

That error indicates the ACI container is still not ready. The error should stop once the container is in ready status. We might need to change the error message to be more clear. 

The `1.4.5` release shouldn't have this message, May I ask if you can try to install the helm chart for `1.4.5` one more time?

**Comment by helayoty** [comment]
A new version `1.4.8` has been released today that will address this issue. You can use it by installing the helm chart in your cluster. This version will be available as a default addon for the Virtual Node by Jan 2023.

https://github.com/virtual-kubelet/azure-aci/releases/tag/1.4.8
