### ISSUE TITLE
horizontal pod autoscaler with ACI

### ISSUE THREAD

**Issue by ksauce** [virtual-kubelet/azure-aci#38]
The Kubernetes horizontal pod autoscaler failed to get memory and cpu resources on the pods deployed to ACI.  Is this a supported feature?   If not how would we be able to control auto scaling?

hpa:
  {"apiVersion":"autoscaling/v2beta2","kind":"HorizontalPodAutoscaler"

Metrics:                                                  ( current / target )
  resource memory on pods  (as a percentage of request):   <unknown> / 70%
  resource cpu on pods  (as a percentage of request):       <unknown> / 70%
Min replicas:                                             2

Events:
  Type     Reason                        Age                      From                       Message
  ----     ------                        ----                     ----                       -------
  Warning  FailedComputeMetricsReplicas  31m (x11360 over 2d1h)   horizontal-pod-autoscaler  failed to get memory utilization: unable to get metrics for resource
 memory: no metrics returned from resource metrics API
  Warning  FailedGetScale                26m (x46 over 5h14m)     horizontal-pod-autoscaler  deployments/scale.apps "xxxxxxxxx" not found
  Warning  FailedGetResourceMetric       117s (x11453 over 2d1h)  horizontal-pod-autoscaler  unable to get metrics for resource memory: no metrics returned from

**Comment by ibabou** [comment]
@ksauce Can you please share more information on the VN setup you have, Is it Linux ? and is it installed through Add-on or is it through a custom/Helm installation ? Also, what is the region/rg used by your AKS cluster ?

**Comment by ibabou** [comment]
@ksauce , it'll be helpful if you can share the VK pod's spec -- especially the virtual-kubelet container itself.

**Comment by ksauce** [comment]
Linux
Installed via virtual add on:   https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli 
Region: West US

kubectl describe pods aci-connector-linux-westus-virtual-kubelet-for-aks-665c446prblh

Name:           aci-connector-linux-westus-virtual-kubelet-for-aks-665c446prblh
Namespace:      default
Priority:       0
Node:           aks-nodepool1-13385978-vmss000006/10.240.0.4
Start Time:     Fri, 24 Jan 2020 12:51:45 -0800
Labels:         app=aci-connector-linux-westus-virtual-kubelet-for-aks
                pod-template-hash=665c446775
Annotations:    <none>
Status:         Running
IP:             xxxxxx
Controlled By:  ReplicaSet/aci-connector-linux-westus-virtual-kubelet-for-aks-665c446775
Containers:
  aci-connector-linux-westus-virtual-kubelet-for-aks:
    Container ID:  docker://2bcf97487b47ba1d740dc5130e3468d9de3d64a060f6e9f3c1c49cfbaed233e9
    Image:         microsoft/virtual-kubelet:latest
    Image ID:      docker-pullable://microsoft/virtual-kubelet@sha256:efc397d741d7e590c892c0ea5dccc9a800656c3adb95da4dae25c1cdd5e
    Port:          <none>
    Host Port:     <none>
    Command:
      virtual-kubelet
    Args:
      --provider
      azure
      --namespace

      --nodename
      virtual-kubelet-aci-connector-linux-westus
      --os
      Linux
    State:          Running
      Started:      Fri, 24 Jan 2020 12:51:48 -0800
    Ready:          True
    Restart Count:  0
    Environment:
      KUBELET_PORT:             10250
      ACS_CREDENTIAL_LOCATION:  /etc/acs/azure.json
      AZURE_TENANT_ID:          xxxxxx
      AZURE_SUBSCRIPTION_ID:    xxxxxxxx
      AZURE_CLIENT_ID:
      AZURE_CLIENT_SECRET:      <set to the key 'clientSecret' in secret 'aci-connector-linux-westus-virtual-kubelet-for-aks'>  O
      ACI_RESOURCE_GROUP:
      ACI_REGION:               westus
      APISERVER_CERT_LOCATION:  /etc/virtual-kubelet/cert.pem
      APISERVER_KEY_LOCATION:   /etc/virtual-kubelet/key.pem
      VKUBELET_POD_IP:           (v1:status.podIP)
      ACI_EXTRA_USER_AGENT:     helm-chart/aks/virtual-kubelet-for-aks/0.1.10
      ACI_SUBNET_NAME:
      ACI_SUBNET_CIDR:
      MASTER_URI:               https://xxxx-xxxxxx-a77c1d-66c09aea.hcp.westus.azmk8s.io
      CLUSTER_CIDR:
      KUBE_DNS_IP:
    Mounts:
      /etc/acs/azure.json from acs-credential (rw)
      /etc/virtual-kubelet from credentials (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from aci-connector-linux-westus-virtual-kubelet-for-aks-token-zfrtf (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  aci-connector-linux-westus-virtual-kubelet-for-aks
    Optional:    false
  acs-credential:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  aci-connector-linux-westus-virtual-kubelet-for-aks-token-zfrtf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  aci-connector-linux-westus-virtual-kubelet-for-aks-token-zfrtf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**Comment by ibabou** [comment]
Thanks @ksauce for the update! So the messages you shared above can normally happen till the pod gets up on ACI side. Now, to confirm about that, can you share the list of pods created by your deployment and its current state ? and double check the logs of connector to see if you still continuously seeing the error ?

Metrics are supported for Linux VNs. One other case when you might see these errors, Is because of freshness timing (when ACI collects metrics and push it to its storage) and when metrics-server or anyone hits the metrics endpoint of VN to collect stats. But in this case the HPA will still function, as it’ll be able to pick up the metrics for the replicas in the next cycle.

**Comment by ksauce** [comment]
kubectl get pods
NAME                                                              READY   STATUS    RESTARTS   AGE
aci-connector-linux-westus-virtual-kubelet-for-aks-665c446prblh   1/1     Running   0          
pagecompositionservice-76dc6bc47d-2w5ws                           3/3     Running   0         
pagecompositionservice-76dc6bc47d-hr6jt                           3/3     Running   1      


I set the HPA to scale up on > 2 % CPU 
 metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 2

 I am running load containers instances and observe via the average CPU for the container is above this amount. 



No errors related to metrics.  Just following:
    
time="2020-01-28T03:57:53Z" level=error msg="Error while handling node ping" error="failed to patch status \"{\\\"metadata\\\":{\\\"resourceVersion\\\":null},\\\
"status\\\":{\\\"$setElementOrder/conditions\\\":[{\\\"type\\\":\\\"Ready\\\"},{\\\"type\\\":\\\"OutOfDisk\\\"},{\\\"type\\\":\\\"MemoryPressure\\\"},{\\\"type\\
\":\\\"DiskPressure\\\"},{\\\"type\\\":\\\"NetworkUnavailable\\\"}],\\\"conditions\\\":[{\\\"lastHeartbeatTime\\\":\\\"2020-01-28T03:57:45Z\\\",\\\"type\\\":\\\"
Ready\\\"},{\\\"lastHeartbeatTime\\\":\\\"2020-01-28T03:57:45Z\\\",\\\"type\\\":\\\"OutOfDisk\\\"},{\\\"lastHeartbeatTime\\\":\\\"2020-01-28T03:57:45Z\\\",\\\"ty
pe\\\":\\\"MemoryPressure\\\"},{\\\"lastHeartbeatTime\\\":\\\"2020-01-28T03:57:45Z\\\",\\\"type\\\":\\\"DiskPressure\\\"},{\\\"lastHeartbeatTime\\\":\\\"2020-01-
28T03:57:45Z\\\",\\\"type\\\":\\\"NetworkUnavailable\\\"}]}}\" for node \"virtual-kubelet-aci-connector-linux-westus\": etcdserver: request timed out" namespace=
 node=virtual-kubelet-aci-connector-linux-westus operatingSystem=Linux provider=azure
time="2020-01-28T19:01:42Z" level=info msg="Created pod in provider" key=default/pagecompositionservice-76dc6bc47d-fxlk8 method=createOrUpdatePod name=pagecompos
itionservice-76dc6bc47d-fxlk8 namespace=default node=virtual-kubelet-aci-connector-linux-westus operatingSystem=Linux phase=Pending pod=pagecompositionservice-76
dc6bc47d-fxlk8 provider=azure reason= uid=9b8f67d1-4200-11ea-b5df-5e2d581b3045 workerId=10
time="2020-01-28T19:01:45Z" level=warning msg="skipping update of pod [[[[pagecompositionservice-76dc6bc47d-fxlk8]]]] as pod updates are not supported" key=defau
lt/pagecompositionservice-76dc6bc47d-fxlk8 method=syncPodInProvider name=pagecompositionservice-76dc6bc47d-fxlk8 namespace=default node=virtual-kubelet-aci-conne
ctor-linux-westus operatingSystem=Linux phase=Pending provider=azure reason= uid=9b8f67d1-4200-11ea-b5df-5e2d581b3045 workerId=10
time="2020-01-28T19:01:46Z" level=info msg="Created pod in provider" key=default/pagecompositionservice-76dc6bc47d-wv2t2 method=createOrUpdatePod name=pagecompos
itionservice-76dc6bc47d-wv2t2 namespace=default node=virtual-kubelet-aci-connector-linux-westus operatingSystem=Linux phase=Pending pod=pagecompositionservice-76
dc6bc47d-wv2t2 provider=azure reason= uid=9b8ade64-4200-11ea-b5df-5e2d581b3045 workerId=10
time="2020-01-28T19:01:51Z" level=warning msg="skipping update of pod [[[[pagecompositionservice-76dc6bc47d-wv2t2]]]] as pod updates are not supported" key=defau
lt/pagecompositionservice-76dc6bc47d-wv2t2 method=syncPodInProvider name=pagecompositionservice-76dc6bc47d-wv2t2 namespace=default node=virtual-kubelet-aci-conne
ctor-linux-westus operatingSystem=Linux phase=Pending provider=azure reason= uid=9b8ade64-4200-11ea-b5df-5e2d581b3045 workerId=10

**Comment by ibabou** [comment]
@ksauce Do you see any scale-up events ? Are you using kubectl top command to monitor the cpu utilization of these replicas ? Can you please share the output ?. I'm afraid in this case the scaling is not happening at all.

One thing to mention as a side, can you please use the add-on command to add the VN to your cluster ?
az aks enable-addons \
    --resource-group <your resource group> \
    --name <your cluster name> \
    --addons virtual-node \
    --subnet-name virtual-node-aci

I guess the AKS cluster you've already uses "Advanced Networking" type ?

This will make sure you always have the latest bits up-to-date, and VNET integration. The other clis "install" & "remove" just uses helm that currently deploy an old version "v0.9". We are deprecating it.

**Comment by ksauce** [comment]
yes I have the virtual-node add on for the cluster.  AKS cluster is advanced Networking type.  No the top nodes does not report any metrics.

![image](https://user-images.githubusercontent.com/21204007/73306140-6dd68600-41d0-11ea-8db3-baf7944ec04c.png)

**Comment by ksauce** [comment]
Why do I have a virtual-node-aci and virtual-kubelet-aci-connector in the cluster?  Which should I be using?

![image](https://user-images.githubusercontent.com/21204007/73306811-d07c5180-41d1-11ea-87b6-25257778d6d9.png)


![image](https://user-images.githubusercontent.com/21204007/73306909-01f51d00-41d2-11ea-92ac-8a71167301c0.png)

**Comment by ksauce** [comment]
and removing and enable az aks enable-addons
--resource-group
--name
--addons virtual-node
--subnet-name virtual-node-aci

installs the virtual-node-aci-linux.  This results in my pods terminated and restarting.  Where are the  logs to find out why it restarted the pods ?

**Comment by ibabou** [comment]
@ksauce It'll be hard to debug having both deployed. I think the old one maybe exists from a previous manual deployment when you used the deprecated clis. I'm talking here about virtual-kubelet-aci-connector-linux-westus node. 
To remove it, you can simply use "helm list" to find its corresponding release and then do a "helm uninstall release_name". this should remove the virtual-kubelet-aci-connector-linux-westus node's connector. after deleting the helm release, follow that with "kubectl delete node virtual-kubelet-aci-connector-linux-westus.

If the metrics shown are still under 1%, this makes sense why scaling up wasn't happening in this last attempt.

However looking on the backend logs from our end, I see there is pods went on virtual-node-aci-linux corresponding to one deployment on AKS cluster "". Below is the history for creations/deletions of these. Were you trying manual scaling on this ? 

2020-01-27T23:18:08.4199248Z	PUT		*/*pagecompositionservice-76dc6bc47d-cjvbb
2020-01-27T23:19:24.4673793Z	PUT		*/*pagecompositionservice-76dc6bc47d-bl42m
2020-01-27T23:20:40.7636822Z	PUT		*/*pagecompositionservice-76dc6bc47d-r8gvx
2020-01-27T23:22:39.0379882Z	DELETE		*/*pagecompositionservice-76dc6bc47d-r8gvx
2020-01-27T23:22:40.5760129Z	PUT		*/*pagecompositionservice-76dc6bc47d-d2hzq
2020-01-27T23:30:18.1611839Z	DELETE		*/*pagecompositionservice-76dc6bc47d-cjvbb
2020-01-27T23:30:18.1787722Z	DELETE		*/*pagecompositionservice-76dc6bc47d-d2hzq
2020-01-27T23:30:18.2286545Z	DELETE		*/*pagecompositionservice-76dc6bc47d-bl42m
2020-01-28T19:01:42.6699745Z	PUT		*/*pagecompositionservice-76dc6bc47d-4qrcj
2020-01-28T19:01:43.5863214Z	PUT		*/*pagecompositionservice-76dc6bc47d-fxlk8
2020-01-28T19:01:47.9190265Z	PUT		*/*pagecompositionservice-76dc6bc47d-wv2t2
2020-01-28T20:20:08.0296539Z	DELETE		*/*pagecompositionservice-76dc6bc47d-wv2t2
2020-01-28T20:20:08.0541727Z	DELETE		*/*pagecompositionservice-76dc6bc47d-4qrcj
2020-01-28T20:20:08.0907039Z	DELETE		*/*pagecompositionservice-76dc6bc47d-fxlk8
2020-01-28T20:20:24.9318092Z	PUT		*/*pagecompositionservice-76dc6bc47d-2w5ws
2020-01-28T20:20:25.6833204Z	PUT		*/*pagecompositionservice-76dc6bc47d-hr6jt
2020-01-28T20:26:42.6191053Z	DELETE		*/*pagecompositionservice-76dc6bc47d-hr6jt
2020-01-28T20:26:42.8360348Z	DELETE		*/*pagecompositionservice-76dc6bc47d-2w5ws
2020-01-28T20:26:46.9147539Z	PUT		*/*pagecompositionservice-76dc6bc47d-fr8ln
2020-01-28T20:26:48.6641768Z	PUT		*/*pagecompositionservice-76dc6bc47d-gpljd
2020-01-28T20:59:08.8145369Z	PUT		*/*pagecompositionservice-76dc6bc47d-rm6kg
2020-01-28T20:59:08.8672908Z	PUT		*/*pagecompositionservice-76dc6bc47d-8jhsr
2020-01-28T20:59:11.3951351Z	PUT		*/*pagecompositionservice-76dc6bc47d-bjwz2
2020-01-28T21:36:49.2984304Z	DELETE		*/*pagecompositionservice-76dc6bc47d-fr8ln
2020-01-28T21:36:49.3268343Z	DELETE		*/*pagecompositionservice-76dc6bc47d-gpljd
2020-01-28T21:36:49.3685009Z	DELETE		*/*pagecompositionservice-76dc6bc47d-rm6kg
2020-01-28T21:36:49.3712126Z	DELETE		*/*pagecompositionservice-76dc6bc47d-bjwz2
2020-01-28T21:36:49.4130891Z	DELETE		*/*pagecompositionservice-76dc6bc47d-8jhsr
2020-01-28T22:01:30.4932544Z	PUT		*/*pagecompositionservice-76dc6bc47d-7tspf
2020-01-28T22:02:23.8068007Z	DELETE		*/*pagecompositionservice-76dc6bc47d-7tspf
2020-01-28T22:02:51.7733582Z	PUT		*/*pagecompositionservice-76dc6bc47d-b4szk
2020-01-28T22:03:04.9682261Z	PUT		*/*pagecompositionservice-76dc6bc47d-nwkf7
2020-01-28T22:19:28.8667684Z	DELETE		*/*pagecompositionservice-76dc6bc47d-nwkf7
2020-01-28T22:19:32.5469608Z	DELETE		*/*pagecompositionservice-76dc6bc47d-b4szk
2020-01-28T22:19:34.9049239Z	PUT		*/*pagecompositionservice-76dc6bc47d-h4f6t
2020-01-28T22:20:09.0814005Z	PUT		*/*pagecompositionservice-76dc6bc47d-g5mq5
2020-01-28T22:49:51.2603762Z	DELETE		*/*pagecompositionservice-76dc6bc47d-h4f6t
2020-01-28T22:49:51.4616254Z	DELETE		*/*pagecompositionservice-76dc6bc47d-g5mq5
2020-01-28T22:50:02.3379988Z	PUT		*/*pagecompositionservice-76dc6bc47d-c7hvj
2020-01-28T22:50:02.3433298Z	PUT		*/*pagecompositionservice-76dc6bc47d-8w8b5

Last two replicas seem to be up and running. Are these running and healthy ?

For logs, you can use kubectl logs, or directly check the ACI resources. but this won't work for CGs that got deleted.

**Comment by macolso** [comment]
Just as a heads up for feature reference - we don't support sending logs to log analytics for pods spun out by virtual node @ksauce. We do have plans to incorporate in the first half of 2020.

**Comment by ksauce** [comment]
So with the older version of the virtual-kubelet-aci-connector-linux-westus there were no restarts.  My pods were running fine.  Running with the v1.14.3-vk-azure-aci-v1.2.1 , they have restarted 287 times .  As mentioned there are no logs so I wouldn't know what is happening.

**Comment by ksauce** [comment]
Errors from the connector:

level=error msg="failed to retrieve pod xxxxxx status from provider

Sending get container gr
oup request failed: Get https://management.azure.com/subscriptions/xxxxxxx?api-version=2018-10-01: stream error: stream ID 65; CA
NCEL" method=PodsTracker.processPodUpdates node=virtual-node-aci-linux operatingSystem=Linux provider=azure watchedNamespace=

**Comment by ibabou** [comment]
@ksauce this log is fine, in some cases after the VK issues a delete to CG (if it got deleted from api-server and so marked to be deleted "Terminating" state), this monitor remains trying to see if it is still available on ACI side.

I see now that all deployments after 29th are coming through add-on only. which is good.

Can you please share the full logs of connector (of add-on's connector) -- after you create a new deployment. you can locate this pod by looking for:
kubectl get pods -n kube-system -l app=aci-connector-linux -o wide

**Comment by ibabou** [comment]
Following up with @ksauce offline. seems restarts are not happening on latest AKS + VN without vnets. Closing for now.

**Comment by AlexeyRaga** [comment]
Hello,

I am having the same issue right now using Kubernetes 1.18.4:

```
time="2020-07-22T01:09:58Z" level=error msg="cleaning up dangling pod speechmatics-64bbc6757c-zv77d" method=PodsTracker.cleanupDanglingPods node=virtual-node-aci-linux operatingSystem=Linux provider=azure watchedNamespace=
time="2020-07-22T01:09:59Z" level=error msg="cleaning up dangling pod speechmatics-64bbc6757c-zv7wx" method=PodsTracker.cleanupDanglingPods node=virtual-node-aci-linux operatingSystem=Linux provider=azure watchedNamespace=
...
```

My ACI connector properties are as follow:

```
$ kubectl get pods -n kube-system -l app=aci-connector-linux -o wide
NAME                                   READY   STATUS    RESTARTS   AGE     IP            NODE                              NOMINATED NODE   READINESS GATES
aci-connector-linux-6cd4cf86b6-znnv7   1/1     Running   7          4h33m   10.210.10.8   aks-default-10715501-vmss000000   <none>           <none>
```

```
$ kubectl get nodes -o wide
NAME                              STATUS   ROLES   AGE    VERSION                         INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-default-10715501-vmss000000   Ready    agent   6d3h   v1.18.4                         10.210.10.4   <none>        Ubuntu 16.04.6 LTS   4.15.0-1089-azure   docker://3.0.10+azure
virtual-node-aci-linux            Ready    agent   6d3h   v1.14.3-vk-azure-aci-v1.2.1.1   10.210.10.8   <none>        <unknown>            <unknown>           <unknown>
```

I see that Kubernetes thinks that there are pods in the system, and even reports that some pods are in a "Ready" state. None of the pods are in "Terminating" state, only "Running", "Waiting" and "Pending", and they've been in this state for >3 hours already.
But when I look at ACI then I see no container groups that are currently running there, so Kubernetes is obviously wrong here.
