### ISSUE TITLE
VK gets in error state after short amount of time

### ISSUE THREAD

**Issue by scabana** [virtual-kubelet/azure-aci#39]
Hi, 

We've been having problems with the VK getting in a state where it doesn't schedule the pods for the deployments after a short amount of time. 

Timeline: 
- 2020-01-20: provision new aks cluster
- 2020-01-20: install VK virtualkubelet.azurecr.io/virtual-kubelet:1.2.1
- 2020-01-20: create a deployment that should be on ACI
- 2020-01-20: deployment's pods are scheduled by the VK, all is fine
- 2020-01-21: error messages below (logs 1)
- 2020-01-28: try to scale out the deployment, nothing happens
- 2020-01-28: try to scale in (0 replicas) the deployment, current pod destroyed
- 2020-01-28: try to scale out the deployment, nothing happens (no logs at all after the time the deployment was scaled)
- 2020-01-28: waited 5 minutes, nothing else happened

Logs 1: 
```
time="2020-01-21T11:15:44Z" level=error msg="failed to retrieve pod ***-7ddd867bd5-csnxw status from provider" error="api call to https://management.azure.com/subscriptions/***/resourceGroups/MC_***/providers/Microsoft.ContainerInstance/containerGroups/dev-***-7ddd867bd5-csnxw?api-version=2018-10-01: got HTTP response status code 401 error code \"AuthorizationFailed\": A client certificate was not provided." method=PodsTracker.processPodUpdates node=virtual-kubelet-aci-connector-for-windows operatingSystem=Windows provider=azure watchedNamespace=
time="2020-01-21T15:49:00Z" level=error msg="failed to retrieve pod ***-7ddd867bd5-csnxw status from provider" error="api call to https://management.azure.com/subscriptions/***/resourceGroups/MC_***/providers/Microsoft.ContainerInstance/containerGroups/dev-***-7ddd867bd5-csnxw?api-version=2018-10-01: got HTTP response status code 500 error code \"MultipleErrorsOccurred\": Multiple error occurred: ." method=PodsTracker.processPodUpdates node=virtual-kubelet-aci-connector-for-windows operatingSystem=Windows provider=azure watchedNamespace=
W0121 17:24:44.282776       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190805141520-2fe0317bcee0/tools/cache/reflector.go:98: watch of *v1.Pod ended with: too old resource version: 124308 (127966)
W0121 23:36:41.389428       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190805141520-2fe0317bcee0/tools/cache/reflector.go:98: watch of *v1.Pod ended with: too old resource version: 271526 (277234)
W0122 14:28:05.649086       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190805141520-2fe0317bcee0/tools/cache/reflector.go:98: watch of *v1.Pod ended with: too old resource version: 346066 (346178)
W0122 17:03:05.692184       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190805141520-2fe0317bcee0/tools/cache/reflector.go:98: watch of *v1.Pod ended with: too old resource version: 518175 (519580)
W0122 20:03:30.743901       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190805141520-2fe0317bcee0/tools/cache/reflector.go:98: watch of *v1.Pod ended with: too old resource version: 552086 (553110)
W0123 07:32:53.945951       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190805141520-2fe0317bcee0/tools/cache/reflector.go:98: watch of *v1.Pod ended with: too old resource version: 590996 (591015)
W0123 17:51:18.127390       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190805141520-2fe0317bcee0/tools/cache/reflector.go:98: watch of *v1.Pod ended with: too old resource version: 725482 (727407)
W0123 21:32:34.191593       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190805141520-2fe0317bcee0/tools/cache/reflector.go:98: watch of *v1.Pod ended with: too old resource version: 846860 (854079)
time="2020-01-24T01:04:26Z" level=error msg="Internal server error on request" error="error getting status from provider: error in request to fetch container group metrics: error fetching cpu/mem stats for container group dev-***-7ddd867bd5-csnxw: sending get container group metrics request failed: Get https://management.azure.com/subscriptions/***/resourceGroups/MC_***/providers/Microsoft.ContainerInstance/containerGroups/dev-***-7ddd867bd5-csnxw/providers/microsoft.Insights/metrics?%24filter=containerName+eq+%27%2A%27&aggregation=average&api-version=2018-01-01&interval=PT1M&metricnames=CpuUsage%2CMemoryUsage&timespan=2020-01-24T01%3A02%3A46Z%2F2020-01-24T01%3A03%3A46Z: context canceled" httpStatusCode=500 uri=/stats/summary vars="map[]"
```

**Comment by scabana** [comment]
Additional information: 

- Clarification: Trying to provision windows containers
- The VK was installed as if it was not on an aks cluster. Provisioning of the pods were working, but then stops working
- Re-installed the helm chart targetting `providers.azure.targetAKS=true` plus other parameters, now, I get this log:
    ```
    time="2020-01-28T14:09:15Z" level=warning msg="requeuing \"dev/***-7ddd867bd5-nsxhz\" due to failed sync" error="failed to sync pod \"dev/***-7ddd867bd5-nsxhz\" in the provider: api call to https://management.azure.com/subscriptions/***/resourceGroups/MC_dems-dev_dems-dev-6-eastus-aks_eastus/providers/Microsoft.ContainerInstance/containerGroups/dev-***-7ddd867bd5-nsxhz?api-version=2018-10-01: got HTTP response status code 400 error code \"DnsConfigNotSupportedOnWindows\": DNS config is not supported on Windows yet." key=dev/***-7ddd867bd5-nsxhz method=handleQueueItem node=virtual-kubelet-aci-connector-for-windows operatingSystem=Windows provider=azure watchedNamespace= workerId=9
    ```

**Comment by ibabou** [comment]
@scabana, so VK integration for windows currently has many limitations:
1- byo-VNET isn't fully supported, as well as using special DNS configuration (which VK uses internally in case of VNET to set the dns nameserver). So please when installing through helm, pass the following "--set providers.azure.vnet.enabled=false --set providers.azure.vnet.subnetName= ".
2- Currently metrics is not supported for windows either, as it is not available through ACI's created Monitoring storage. It's normal to see the retrieval errors as metrics-server will keep trying to scrape through VN's stats endpoint. This means also that HPA-based scaling won't work in this case.

One question, in the initial setup, when you scaled up the deployment manually, what was the state of the pods created by k8s ? was it kept in Pending state ?

**Comment by scabana** [comment]
@ibabou 
1- ok! that's what I ended up doing
2- Good to know those errors are expected! As for the HPA, we didn't have one configured for that specific deployment. 

On the 20th, manual scale in and scale out worked. It works for a small while and then does nothing for scale out. I would really like to see the pattern as to when it stops working.

**Comment by ibabou** [comment]
> @ibabou

> 
> On the 20th, manual scale in and scale out worked. It works for a small while and then does nothing for scale out. I would really like to see the pattern as to when it stops working.

Can you please elaborate on works for small ? So when you start creating larger number of replicas, the pods created go in Failed pending state ? What was the size of replicaset when you saw it failing ?

**Comment by scabana** [comment]
It works for a few hours/days then stops working. It doesn't seem related to the number of replicas. We tried with 100 replicas, worked well. Came back a day later, wouldn't work anymore. 

Would opening a support ticket on the azure portal help? We could(maybe) then connect directly.

**Comment by ibabou** [comment]
@scabana Sounds good, please open a ticket for further investigation.

But I still would like to get more context about the behavior you stated above:
1- you mentioned scaling out the existing deployment you had earlier — which was successful, didn’t work out.
2- then scaling-down worked, but again scaling-out back didn’t work out.

Can you share with me what was the pods state in these cases ? Did you see K8s creating the additional pods however VK connector didn’t pick it up and so it was kept in Pending state forever ?

Also it’ll be helpful if you can share with me the deployment name in which you saw this behavior ?, so I can track it and lookup the CGs creations on ACI side — if any happened during (1) or (2) ?

**Comment by scabana** [comment]
Opened a ticket, with a reference to this issue. Sorry for the delay. 

I also created a new cluster with minimal resources in order to repro the issue. It did the same.

Scaling out the deployment works, but the pods stays pending until the VK connector gets restarted. So: "Pending state forever" is right.

I'd rather not share cluster name on here, is there a private way I can do that?

**Comment by macolso** [comment]
Hi Scabana - you can email myself and Ibrahim at macolso@micrsoft.com; ibabou@microsoft.com
