### ISSUE TITLE
Dangling ACI resources left after pods are deleted

### ISSUE THREAD

**Issue by uveta** [virtual-kubelet/azure-aci#409]
**Describe the Issue**
In certain scenarios, when pods are deleted due to scale-in, a matching ACI resource might be left running indefinitely. This has a detrimental impact on the cost of our infrastructure, as running ACI resources are still billed, and have to be removed manually. Our issue was previously reported as part of #378, but no changes to azure-aci since then have solved the underlying problem.

**Steps To Reproduce**
1. Use a larger windows image as a scalable container base. In our case, we are using _mcr.microsoft.com/windows/servercore:ltsc2019_
2. Increase workload to initiate scale-out and create new pods. In our case, we are scaling via Service Bus trigger.
3. New pods are started and, subsequently, new ACI resources are created.
4. Most of the time, it can take up to 10-15 minutes for ACI to pull an image and start a container.
5. While ACI is provisioned, due to missing workload, scale-in operation occurs and pods are deleted from AKS.
6. After being provisioned, ACI resource is left running indefinitely.

**Expected behavior**
Even if matching pod is deleted during ACI provisioning, ACI should be eventually removed.

**Virtual-kubelet version**
1.48

**Kubernetes version**
1.24.6

**Additional context**
All resources, including AKS, container registry, and ACI, are deployed to West Europe region.
I have previously included azure-aci [pod logs](https://gist.github.com/uveta/cade31a76b5c202a1725f538925219a5) from one such occurrence, captured for version 1.47. They are more or less the same in version 1.48 as well.

**Comment by helayoty** [comment]
This issue should be resolved with the latest release `1.4.16`.

**Comment by uveta** [comment]
> This issue should be resolved with the latest release `1.4.16`.

I have tried updating to version `1.4.16`, but now pod provisioning fails with error

`Failed to pull image "mcr.microsoft.com/oss/virtual-kubelet/init-validation:0.2.0": rpc error: code = NotFound desc = failed to pull and unpack image "mcr.microsoft.com/oss/virtual-kubelet/init-validation:0.2.0": failed to resolve reference "mcr.microsoft.com/oss/virtual-kubelet/init-validation:0.2.0": mcr.microsoft.com/oss/virtual-kubelet/init-validation:0.2.0: not found`

**Comment by helayoty** [comment]
> I have tried updating to version `1.4.16`, but now pod provisioning fails with error
> 
> `Failed to pull image "mcr.microsoft.com/oss/virtual-kubelet/init-validation:0.2.0": rpc error: code = NotFound desc = failed to pull and unpack image "mcr.microsoft.com/oss/virtual-kubelet/init-validation:0.2.0": failed to resolve reference "mcr.microsoft.com/oss/virtual-kubelet/init-validation:0.2.0": mcr.microsoft.com/oss/virtual-kubelet/init-validation:0.2.0: not found`

@uveta This should be fixed now. The mcr pipeline needed an additional approval.

**Comment by uveta** [comment]
> @uveta This should be fixed now. The mcr pipeline needed an additional approval.

@helayoty Thanks. I can confirm that `1.4.16` version has been deployed successfully. So far so good. We will continue to monitor for initial issue, as it usually shows up after some time.

**Comment by helayoty** [comment]
@uveta Is it ok to consider this issue as solved now?

**Comment by uveta** [comment]
Thanks @helayoty, everything is looking fine. We have been running new version for a week already. I think the issue can be closed, and I will report any, if they reappear.
