### ISSUE TITLE
Unable to install virtual-kubelet on kubernetes version 1.16

### ISSUE THREAD

**Issue by TheDruidsKeeper** [virtual-kubelet/azure-aci#43]
Trying to install the virtual kubelet (using azure cli version 2.3.1 & kubernetes version 1.16.7):
`az aks install-connector --resource-group group --name cluster --connector-name virtual-kubelet --os-type Windows`

Gives the following error:

> This command is in preview. It may be changed/removed in a future release.
> Deploying the ACI connector for 'Windows' using Helm
> Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by TheDruidsKeeper** [comment]
I'm guessing it's because of the deprecated api's being removed in 1.16: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by macolso** [comment]
Hi @TheDruidsKeeper ~ the ```az aks install-connector``` command will deprecated in the coming month. For the most up-to-date Virtual Kubelet experience on AKS, we recommend Helm chart installation. If you a more managed Virtual Kubelet experience on AKS, we recommend Virtual Node (currently only available for Linux OS).
