### ISSUE TITLE
The deployment uses a deprecated apiversion for kubernetes 1.16

### ISSUE THREAD

**Issue by sledoux** [virtual-kubelet/azure-aci#44]
We recently upgraded our cluster and we're using this:

https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-aci-for-aks.tgz

When deploying this to AKS version 1.16.7 we cannot use kubernetes deployments with api version v1beta1 anymore. This seems to still be referencing it. This needs to be "apps/v1" from kubernetes 1,16 an on.

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"

Expected: The deployment should be using "apiVersion: apps/v1".

**Comment by kenans** [comment]
Hi, any update on this one?

Apart from the `apiVersion` , v1.16 also requires the `selector: matchLabels` to be set explicitly under `deployment.spec` based on my testing.

**Comment by MikkelHegn** [comment]
Fixed
