### ISSUE TITLE
No PodIP

### ISSUE THREAD

**Issue by jperl** [virtual-kubelet/azure-aci#47]
I am using AKS to create a pod on ACI. The pod gets created however it seems that is never receives a pod ip. When I do `kubectl get pod/... -o yaml` I do not see a PodIP.  The pods created on the non-virtual node pool all have PodIP listed.

We need the pod ip to connect to it from other pods.

**Comment by macolso** [comment]
@jperl - are these Linux or Windows pods?

**Comment by jperl** [comment]
It was Linux

**Comment by gossion** [comment]
does the problem still exist, @jperl ? 

Please help to collect below logs that we can take a look
1. describe the pod which does not have pod ip,
2. log of aci connector,
3. log of kube controller manager

**Comment by jperl** [comment]
Hi @gossion unfortunately I don't know since I stopped using AKS.
