### ISSUE TITLE
INSTALLATION FAILED: failed to fetch - 404 Error

### ISSUE THREAD

**Issue by davidskelland** [virtual-kubelet/azure-aci#489]
Hi,

I am getting a 404 Error:

Error: INSTALLATION FAILED: failed to fetch https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-latest.tgz : 404 Not Found

When running the following code:

helm install "virtual-kubelet" "https://github.com/virtual-kubelet/azure-aci/raw/master/charts/virtual-kubelet-latest.tgz" --set provider=azure --set "nodeOsType=Windows" --set providers.azure.targetAKS=true --set providers.azure.masterUri=$MASTER_URI --set nodeName="${NODE_NAME}-win"

What am I doing wrong?

Thanks

**Comment by helayoty** [comment]
@davidskelland Kindly follow [this](https://github.com/virtual-kubelet/azure-aci/tree/master/charts/virtual-kubelet) documentation instead. We are working on updating the Readme file #376

**Comment by helayoty** [comment]
Update: the readme has been updated.

**Comment by davidskelland** [comment]
Thanks Heba,

It seems to have removed all the instructions for deploying the windows version. Is that now available now?


________________________________

**Comment by helayoty** [comment]
> Thanks Heba, It seems to have removed all the instructions for deploying the windows version. Is that now available now?
> […](#)

We have added it [here](https://github.com/virtual-kubelet/azure-aci/blob/master/docs/windows-virtual-node.md) and linked it in the README.
