### ISSUE TITLE
Using managed identity with virtual ACI pods

### ISSUE THREAD

**Issue by Kesudan** [virtual-kubelet/azure-aci#49]
We are currently looking using virtual ACI pods from our AKS cluster.

Is there any way to assign Azure managed identities to pods created through the connector?

We use "AAD Pod Identity" for normal AKS pods, but this has no plans to be supported for the ACI connector
https://github.com/Azure/aad-pod-identity/issues/470

**Comment by MikkelHegn** [comment]
This is not possible today. Tracking as an enhancement.

**Comment by feiskyer** [comment]
AAD Pod Identity requires a daemonset, which is not supported on virtual node.

**Comment by matt-psaltis** [comment]
ACI now shows the option to configure a System or User Managed Identity (preview)
How can we configure this as part of the ACI provisioning process?

**Comment by joanna-jasnowska-wttech** [comment]
Hi, is there any update on this?
