### ISSUE TITLE
ContainerGroupIpAddressType is always 'Public' or 'None'

### ISSUE THREAD

**Issue by mikkelhegn** [virtual-kubelet/azure-aci#54]
ACI supports containers to be exposed on VNETs, and exposes a property if the IpAddress of a container is Public or Private. Currently, the provider only sets the ContainerGroupIpAddressType to "Public" under this condition: https://github.com/virtual-kubelet/azure-aci/commit/e7a368b42672d90d6da4e2d6a015c79ef9e80916, otherwise, it's empty.

This can cause an issue with policies only allowing ContainerGroups with PrivateIPs.

**Comment by helayoty** [comment]
This issue has been fixed. Please feel free to re-open it with more details/updates.
