### ISSUE TITLE
Upgrading virtual node

### ISSUE THREAD

**Issue by lynshi** [virtual-kubelet/azure-aci#564]
**Describe the Issue**
Our virtual node was created many months ago (`277d`) and is on version `v1.19.10-vk-azure-aci-1.4.16`. Is there a way to update the Kubernetes version of the node?

I understand manually installed virtual nodes are not managed by AKS and thus not upgraded automatically, but I'm fairly certain this node was created through AKS. I also cannot find any related `helm` releases, so this virtual node should be a managed one.

**Virtual-kubelet version**
`v1.19.10-vk-azure-aci-1.4.16`

**Kubernetes version**
`v1.26.3`

**Comment by helayoty** [comment]
@lynshi , thanks for contacting us. The current kubernetes version for your virtual node will be the same as your cluster. This is a node naming issue and will be fixed soon.

**Comment by lynshi** [comment]
Just saw that the node has been updated, thanks!
