### ISSUE TITLE
ACI does not support startupProbe after upgrading

### ISSUE THREAD

**Issue by jay-docusign** [virtual-kubelet/azure-aci#566]
**Describe the Issue**
After this change
https://github.com/virtual-kubelet/azure-aci/pull/547
We get this
Warning  ProviderCreateFailed  7m37s (x17 over 18m)  virtual-node-aci-linux/pod-controller  ACI does not support startupProbe

Why was this needed? does anyone have context?

**Steps To Reproduce**

**Expected behavior**
Call the startup probe endpoint?

**Virtual-kubelet version**
1.6.0

**Kubernetes version**

**Additional context**

**Comment by helayoty** [comment]
@jay-docusign , ACI doesn't support startup probes—only readiness and liveness.

**Comment by jay-docusign** [comment]
@helayoty  WHY was this behavior changed?
