### ISSUE TITLE
Update the azure-aci provider version to 1.3 as it's now using VK 1.3

### ISSUE THREAD

**Issue by MikkelHegn** [virtual-kubelet/azure-aci#62]
This PR updated the VK library to 1.3: https://github.com/virtual-kubelet/azure-aci/commit/cadeb6e99263d475a5aa37f320857ca1efab9c9f.

We should bump the aci-provider version to 1.3 as well.

**Comment by mingqishao** [comment]
I have release new version 1.3 with align with Virtual Kubelet.
