### ISSUE TITLE
makefile failing in pipeline

### ISSUE THREAD

**Issue by MikkelHegn** [virtual-kubelet/azure-aci#67]
This PR build failed: https://github.com/virtual-kubelet/azure-aci/pull/66 --> https://app.circleci.com/pipelines/github/virtual-kubelet/azure-aci/163/workflows/7c42813d-530e-4455-ad38-3e40762adabb/jobs/336

```
FAIL
make: *** [Makefile:31: test] Error 1
```

This recent change to the makefile was merged without a pipeline run: https://github.com/virtual-kubelet/azure-aci/commit/ae214601d0d03bafc48b055ffc8d09a9ecca628d - is this causing the issue? And why didn't it trigger a build?

**Comment by cpuguy83** [comment]
The pipeline ran and passed on that one: 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/799078/94064231-37243000-fd9e-11ea-9d64-0ce0798bdb8c.png">

**Comment by cpuguy83** [comment]
Looks like the failure is a timeout in an API call to ACI.

**Comment by feiskyer** [comment]
it is failing because we didn't set a correct `UploadToVKRegistries`. @cpuguy83  do you know which registry should be used in the CI?

**Comment by MikkelHegn** [comment]
The above is valid, but looks like we have issues with some tests, here as well: https://github.com/virtual-kubelet/azure-aci/pull/70#partial-pull-merging

But some of these tests are ok in another test run: https://app.circleci.com/pipelines/github/virtual-kubelet/azure-aci/163/workflows/7c42813d-530e-4455-ad38-3e40762adabb/jobs/336 but the failling test has a different failure (timeout on delete container)

@mingqishao - can you check the actual Container Instance deployments that were part of this test?

Is this a matter of the client needing a longer timeout?

**Comment by MikkelHegn** [comment]
@mingqishao - can you confirm this can be closed?
