### ISSUE TITLE
virtual-kubelet/azure-aci helm charts installation fails due to expired registry secrets.

### ISSUE THREAD

**Issue by subodh-dharma** [virtual-kubelet/azure-aci#80]
I tried installation of virtual-kubelet/azure-aci on AKS 1.17.11, the pods for Linux as well as Windows ACI failed due to invalid credentials.

Helm Charts used: 

https://github.com/virtual-kubelet/azure-aci/tree/e8ec5dee8918cd9b4755a0fe01d9b63d01f95e88/charts

AKS Cluster Version: 1.16.15 and 1.17.11

Error Message:
 ImagePullBackOff for pods deployed using above helm chart.

Detailed Event for Pod:

```yaml
kind: Event
apiVersion: v1
metadata:
  name: >-
    virtual-kubelet-virtual-kubelet-aci-for-aks-7fdb878c89-65265.16463c52d94758d9
  namespace: default
  selfLink: >-
    /api/v1/namespaces/default/events/virtual-kubelet-virtual-kubelet-aci-for-aks-7fdb878c89-65265.16463c52d94758d9
  uid: 81c31b70-1af2-404e-9ff9-a4d7243c302b
  resourceVersion: '16789'
  creationTimestamp: '2020-11-10T19:30:43Z'
involvedObject:
  kind: Pod
  namespace: default
  name: virtual-kubelet-virtual-kubelet-aci-for-aks-7fdb878c89-65265
  uid: 3dec585d-56ba-4b10-9dc3-12484e51062e
  apiVersion: v1
  resourceVersion: '16360'
  fieldPath: 'spec.containers{virtual-kubelet-virtual-kubelet-aci-for-aks}'
reason: Failed
message: >-
  Failed to pull image "virtualkubelet.azurecr.io/virtual-kubelet:1.3.0": [rpc
  error: code = Unknown desc = Error response from daemon: Get
  https://virtualkubelet.azurecr.io/v2/virtual-kubelet/manifests/1.3.0:
  unauthorized: Invalid clientid or client secret., rpc error: code = Unknown
  desc = Error response from daemon: Get
  https://virtualkubelet.azurecr.io/v2/virtual-kubelet/manifests/1.3.0:
  unauthorized: Application not registered with AAD., rpc error: code = Unknown
  desc = Error response from daemon: Get
  https://virtualkubelet.azurecr.io/v2/virtual-kubelet/manifests/1.3.0:
  unauthorized: authentication required, visit https://aka.ms/acr/authorization
  for more information.]
source:
  component: kubelet
  host: aks-group1-34364941-vmss000003
firstTimestamp: '2020-11-10T19:30:43Z'
lastTimestamp: '2020-11-10T19:32:17Z'
count: 4
type: Warning
eventTime: null
reportingComponent: ''
reportingInstance: ''
```

Looks like the values in helm charts that need to be updated is `image.repositoryReadOnlyPrincipalSecret`.

**Comment by cpuguy83** [comment]
@MikkelHegn Looks like this is behind a private acr?

**Comment by subodh-dharma** [comment]
I was able to successfully deploy the above helm charts in the last week. I started getting this error today i.e Nov 10, 2020

**Comment by MikkelHegn** [comment]
There's an issue with access to the registry hosting the image referenced in the Helm chart - we're looking into this asap.

**Comment by MikkelHegn** [comment]
The image is available here: `mcr.microsoft.com/oss/virtual-kubelet/virtual-kubelet:1.3.0` - we need an update to the Helm charts to point to the public repo #82.

**Comment by MikkelHegn** [comment]
@subodh-dharma - heads up on this PR #84 - the aci-for-aks tar has been removed, since it doesn't use versions. Also 1.2.3.1 has been updated. All tars in the charts repo are back to working.

**Comment by subodh-dharma** [comment]
@MikkelHegn I used the `virtual-kubelet-latest.tgz` to deploy the ACI for AKS, both linux and windows type deployments are healthy.

Thank you for the quick turnaround!
