### ISSUE TITLE
Schedule deployment to specific location region

### ISSUE THREAD

**Issue by Romiko** [virtual-kubelet/azure-aci#81]
Hi,

I have two Deployments, how can I deploy one pod to Australia East and another pod to Europe using the virtual kubelet? Is there a way to decorate the node selector with a preferred region that the aci provider can read when scheduling?

**Comment by Romiko** [comment]
Looking at the code, it seems this is possible if I install multiple virtual kubelets with different release names and node names? E..g

Release vkwestus
Node vkwestus

Release vkaustraliaeast
Node vkaustraliaeast

Is this correct? I can then install these charts on Gke?

**Comment by MikkelHegn** [comment]
That is correct

**Comment by Romiko** [comment]
I have been able to achieve this with multiple charts.
