### ISSUE TITLE
[feature request] support Azure File CSI driver

### ISSUE THREAD

**Issue by andyzhangx** [virtual-kubelet/azure-aci#88]
Current azure-aci only supports in-tree azure file driver:
https://github.com/virtual-kubelet/azure-aci/blob/190d6b3e255d558c2b0a8dc9c152f1455e172439/provider/aci.go#L1611-L1631

also need to support [Azure File CSI driver](), in the near future, in-tree driver will be removed, and only CSI driver will be supported, here is the reference code about how to get secret, file share from CSI driver struct:
https://github.com/kubernetes/csi-translation-lib/blob/833303372de1d3df6c92110443c70a4c61b7aa50/plugins/azure_file.go#L167-L174

**Comment by tjgalama** [comment]
It looks like this issue prevents keyvault secrets to be accessed from K8s virtual-nodes. Is there any progress on this issue -or- is there an other way that virtual nodes supports keyvault?

**Comment by andyzhangx** [comment]
Azure File in-tree driver is already deprecated on AKS 1.21, any progress on this?

**Comment by ryanzhang-oss** [comment]
@helayoty will work on this

**Comment by jonathan-fileread** [comment]
> It looks like this issue prevents keyvault secrets to be accessed from K8s virtual-nodes. Is there any progress on this issue -or- is there an other way that virtual nodes supports keyvault?

How does Azure Files CSI work with Keyvault? I'm only seeing instructions online for secrets-store csi driver. if I could get a link / tut - that'd be appreciated!

Thanks!!
