### ISSUE TITLE
GKE Pod terminates

### ISSUE THREAD

**Issue by Romiko** [virtual-kubelet/azure-aci#94]
Hi,

When I run virtual kubelet in GKE with Azure ACI. The pods run correctly but GKE terminates them instead of marking them complete. If I look at the error.

Error from server: Get https://10.176.9.97:10250/containerLogs/my-namespace/myjob-cronjob-1607595600-sq4n7/user-journey: x509: cannot validate certificate for 10.176.9.97 because it doesn't contain any IP SANs

What is the cause of this issue. Would be great if kubernetes can mark it complete. In Azure the container runs to completion.

using virtual node v1.18.4-vk-azure-aci-v1.3.1

Thx

**Comment by ryanzhang-oss** [comment]
I don't think azure ACI supports GKE
