### ISSUE TITLE
How should I go about updating the certificate that comes with the installation?

### ISSUE THREAD

**Issue by eugen-nw** [virtual-kubelet/azure-aci#96]
I recently installed the 1.3.1 VK onto our AKS instances using Helm, following the instructions in the "Deployment of the ACI provider in your cluster" section of the https://github.com/virtual-kubelet/azure-aci/blob/master/README.md document.

I remember from an earlier conversation - https://github.com/virtual-kubelet/azure-aci/issues/30 - that the expiration of that certificate forced us to uninstall and reinstall the VK later on.  I'm wondering if there is an improved process in place this time around, that allows us to leave the VK running and only upgrade the certificate shortly before it expires?

Thanks very much,

eugen

**Comment by feiskyer** [comment]
@eugen-nw please use https://docs.microsoft.com/en-us/azure/aks/virtual-nodes on AKS, so you don't need to care about this.

**Comment by eugen-nw** [comment]
The above https://docs.microsoft.com/en-us/azure/aks/virtual-nodes article does not address our particular issue.  We are running Windows containers so we need to install https://github.com/virtual-kubelet/azure-aci in order to run them.  My original question was what is the procedure in place to update the certificate that component uses before/when it expires without having to remove and reinstall the component.
